/**
 * Bodos Filesystem — eigenständiger Baum, getrennt von Worags.
 *
 * /home enthält NUR /home/bodo. Worags Home liegt nicht hier; auf Worags
 * Daten kommt man von Bodos Konsole nur via `telnet worag.e67`. Das
 * /etc-Verzeichnis ist bewusst dupliziert: Bodos Hausmeister-Konsole
 * läuft vor dem `sysupdate` auf altem CentralOS v2.0, das Banner und
 * /etc/motd unterscheiden sich von Worags Maschine.
 */

export interface FsFile {
  type: "file";
  name: string;
  kind?: "text" | "log" | "image" | "news" | "mail" | "audio" | "config";
  size?: number;
  date?: string;
  /** Optional StoryFlag required to reveal this file. */
  requires?: string;
  content: string[];
}

export interface FsDir {
  type: "dir";
  name: string;
  desc?: string;
  children: FsNode[];
}

export type FsNode = FsFile | FsDir;

export const HOME_PATH_BODO: string[] = ["home", "bodo"];

/**
 * Texte der versteckten Essays in Bodos Home — auch von `telnet bodo.e67`
 * (siehe NET_HOSTS in Terminal.tsx) verwendet, damit beide Wege dieselbe
 * Quelle nutzen.
 */
export const FREIHEIT_TXT: string[] = [
  "── freiheit.txt ──────────────────────────────",
  "",
  "Als Fernmeldetechniker habe ich sechsundzwanzig",
  "Jahre lang damit verbracht, Signale durch Kupfer",
  "und Glasfaser zu jagen. Ich weiß, wie ein System",
  "aussieht, das auf Effizienz getrimmt ist. Doch",
  "jetzt, im sogenannten Vorruhestand in Quadrant",
  "E67, beobachte ich ein anderes System: das",
  "menschliche. Und ich frage mich, ob wir nicht",
  "längst alle in einer Feedback-Schleife gefangen",
  "sind, die wir fälschlicherweise „Leben“ nennen.",
  "",
  "── Die Architektur der verwalteten Freiheit ──",
  "",
  "In unserer Welt ist Freiheit zu einer Variablen",
  "in einem Algorithmus geschrumpft. Wir erhalten",
  "Empfehlungen, Ausgänge elektronisch bei der",
  "zentralen Leitstelle anzukündigen. Es ist kein",
  "Gesetz, es ist eine „Empfehlung“ zur Sicherheit.",
  "Doch genau hier liegt die Falle: Eine Freiheit,",
  "die ständig legitimiert und protokolliert werden",
  "muss, ist keine Freiheit mehr — sie ist eine",
  "Leihgabe des Systems.",
  "",
  "Wahre Handlungsfreiheit fühlt sich für uns",
  "inzwischen fast wie etwas Verbotenes an. Wir",
  "bewegen uns in den Korridoren der E-Quadranten",
  "wie Elektronen in einem fest vorgegebenen Gitter.",
  "Wenn das „ZENTRAL.NETZ“ eine Störung meldet oder",
  "ein Error-Code 4567 erscheint, bleibt der Mensch",
  "stehen. Wir haben gelernt, dass unsere Füße erst",
  "dann gehorchen, wenn das System das Gateway",
  "freischaltet. Die Freiheit ist in E67 zu einem",
  "Trugbild geworden, das nur noch in den kurzen",
  "Momenten existiert, in denen man die kühle",
  "Abendluft spürt, bevor man den Ausgang wieder",
  "meldet.",
  "",
  "── Die Delegation der Verantwortung ──────────",
  "",
  "Die Kehrseite dieser verwalteten Freiheit ist",
  "eine schleichende Erosion der Verantwortung.",
  "Wir haben die moralische Pflicht gegenüber",
  "unseren Nachbarn durch administrative Protokolle",
  "ersetzt. Wenn es im Nebenzimmer Probleme gibt,",
  "ist unser erster Reflex nicht die Handreichung,",
  "sondern die Eingabe am Terminal. Wir rufen die",
  "Leitstelle an, wir warten auf das „Technik-Team“",
  "oder den „Block-Sanitäter“.",
  "",
  "Verantwortung wird in unserer Gesellschaft wie",
  "eine Last empfunden, die man so schnell wie",
  "möglich an den nächsten „Abschnittsverantwort-",
  "lichen“ abgeben möchte. Wir fühlen uns erst dann",
  "entlastet, wenn das Thema bei den „Profis“ liegt.",
  "Doch was passiert mit einer Gesellschaft, in der",
  "niemand mehr die Last des anderen tragen will,",
  "ohne dass ein offizielles Protokoll-Druckstück",
  "dabei erstellt wird? Wir delegieren unser",
  "Menschsein an eine anonyme Leitstelle, die selbst",
  "unter Dienstplan-Engpässen und Krankheiten ächzt.",
  "",
  "── Die Resonanz der Leere ────────────────────",
  "",
  "Vielleicht ist das der Grund für die Popularität",
  "der Schmerz-Radios. Da wir im echten Leben keine",
  "tiefe Verbindung mehr zulassen, suchen wir sie in",
  "der künstlich verstärkten Frequenz des Leids",
  "anderer. Wir konsumieren „Engel-Trauer“ auf 104,6,",
  "weil uns die echten Gefühle in den sterilen",
  "Ein-Zimmer-Wohnungen abhandengekommen sind. Wir",
  "nennen es ein „spirituelles Erlebnis ohne Gott“,",
  "aber in Wahrheit ist es nur die verzweifelte Suche",
  "nach Resonanz in einem isolierten Raum.",
  "",
  "Philosophische Notiz: Wir leiden an einer",
  "„Resonanz-Überlastung“. Nicht, weil wir zu viel",
  "fühlen, sondern weil die Gefühle, die wir",
  "empfangen, nicht mehr zu unserem Handeln passen.",
  "Wir hören den Schmerz, aber wir bewegen uns nicht.",
  "",
  "── Fazit: Die Lücke schließen ────────────────",
  "",
  "Es gibt eine Lücke zwischen dem Menschen, der wir",
  "sein könnten, und dem, der wir in diesem Sektor",
  "sind. Freiheit bedeutet nicht, keine Regeln zu",
  "haben, sondern die Verantwortung für das eigene",
  "Handeln wieder selbst in die Hand zu nehmen —",
  "auch wenn das System keine Bestätigung schickt.",
  "",
  "Verantwortung ist kein Zettel, den man abliefert.",
  "Sie ist der Moment, in dem wir aufhören, auf die",
  "„Zentrale“ zu warten, und anfangen, wieder selbst",
  "die Verbindung herzustellen. Nicht über 104,6,",
  "sondern von Mensch zu Mensch.",
  "",
  "In einer Welt aus Beton und Nährstofflösungen ist",
  "das der einzige Weg, um nicht selbst zu einer",
  "katatonischen Dyskinesie zu erstarren. Wir müssen",
  "lernen, wieder ohne Erlaubnis zu atmen.",
  "",
  "Was glauben Sie: Ist ein System, das uns vor",
  "jedem Risiko schützen will, am Ende die größte",
  "Gefahr für unsere Menschlichkeit?",
  "",
  "                                          — b.",
];

export const LAYARD_TXT: string[] = [
  "── layard.txt ────────────────────────────────",
  "",
  "Das Echo der Drähte: Über die Last der",
  "Verantwortung und das Trugbild der Freiheit",
  "in E67",
  "",
  "Als Fernmeldetechniker habe ich sechsundzwanzig",
  "Jahre lang damit verbracht, Signale von A nach B",
  "zu leiten. Heute, im fahlen Licht meines",
  "Vorruhestands in Zimmer 2612, beobachte ich, wie",
  "wir selbst zu bloßen Signalen in einem",
  "überlasteten System geworden sind. Mein Nachbar",
  "Layard in 2611 — ein Mann, der so still ist, dass",
  "man ihn fast für einen Teil der Wandmontage",
  "halten könnte — ist das perfekte Beispiel für",
  "unsere Zeit. Wir leben Wand an Wand, getrennt",
  "durch Beton und verbunden nur durch das Rauschen",
  "der Frequenzen.",
  "",
  "In unserer Welt des Sektors E67 scheint die",
  "Verantwortung zu einer heißen Kartoffel geworden",
  "zu sein, die man so schnell wie möglich fallen",
  "lässt. Wenn es an der Wand klopft, rufen wir die",
  "Leitstelle; wenn die Leitstelle unterbesetzt ist,",
  "schiebt sie uns in andere Quadranten ab. Wir",
  "haben die moralische Instanz durch ein Protokoll",
  "ersetzt. Das Papier, das Layard durch die Flure",
  "trägt, ist mehr als nur ein medizinischer Bericht",
  "über eine „Resonanz-Überlastung“ — es ist das",
  "physische Manifest unserer Unfähigkeit, einander",
  "ohne behördliche Vermittlung beizustehen. Wir",
  "fühlen uns erst dann sicher, wenn die „Profis“",
  "übernehmen, weil wir verlernt haben, dass",
  "Verantwortung kein Auftrag ist, den man abheftet,",
  "sondern eine Antwort auf die Existenz des anderen.",
  "",
  "Die Freiheit hingegen ist in E67 zu einer bloßen",
  "„Empfehlung“ geschrumpft. Wir sollen unsere",
  "Ausgänge melden, unsere Schritte elektronisch",
  "ankündigen, damit die Leitstelle uns im Falle",
  "eines „Verschwindens“ verwalten kann. Es ist eine",
  "Freiheit im Käfig der totalen Vorhersehbarkeit.",
  "Wahre Handlungsfreiheit fühlt sich für jemanden",
  "wie Layard fast „verboten“ an. Wir sind so sehr",
  "an die „CentralOS“-Updates und die Fehlermeldungen",
  "der Router gewöhnt, dass der eigene Wille wie ein",
  "Systemfehler wirkt.",
  "",
  "Doch das Absurdeste ist unsere Suche nach Gefühl.",
  "Wir ernähren uns von B2-Nährstoffen, die nur nach",
  "Vitaminen schmecken, und kompensieren die",
  "emotionale Leere mit Schmerz-Radios. Wir suchen",
  "die „wahre Essenz des Lebens“ in der Trauer",
  "Fremder, während wir den Menschen direkt neben",
  "uns ignorieren, bis sein rhythmisches Klopfen",
  "den Dienstplan stört. Diese „Engel-Trauer“ auf",
  "104,6 ist ein spirituelles Surrogat — ein",
  "Versuch, Tiefe zu finden, wo wir nur noch",
  "Oberflächen verwalten.",
  "",
  "Vielleicht liegt die einzige Freiheit, die uns",
  "bleibt, in jenem Moment, in dem Layard sich",
  "entscheidet, das Protokoll trotz der Stille im",
  "Raum 467 nicht wegzuwerfen. Freiheit ist in",
  "dieser Welt nicht die Abwesenheit von Regeln,",
  "sondern der Mut, die „Lücke“ zwischen dem, der",
  "man ist, und dem, der man sein möchte, zu",
  "schließen.",
  "",
  "Solange wir noch die „milde Abendkälte“ auf der",
  "Haut spüren können, wenn wir den Komplex",
  "verlassen, gibt es Hoffnung. Aber als Techniker",
  "sage ich Ihnen: Die Leitungen sind marode. Wenn",
  "wir nicht lernen, wieder echte Resonanz",
  "zueinander aufzubauen — ohne Funkverbindung und",
  "ohne Verstärker —, dann wird das Klopfen an der",
  "Wand irgendwann verstummen, und niemand wird",
  "mehr da sein, der die 001 wählt.",
  "",
  "                                          — b.",
];

const HOME_BODO: FsDir = {
  type: "dir",
  name: "bodo",
  desc: "Persönliches Verzeichnis — Marschke, B.",
  children: [
    {
      type: "file",
      name: "lotti.txt",
      kind: "text",
      size: 480,
      date: "—",
      content: [
        "── notiz an mich, weil ich vergesse ─────────",
        "",
        "wenn du heute morgen wieder nicht weißt, warum",
        "du aufgestanden bist:",
        "",
        "          LOTTI.",
        "",
        "vierzehn jahre, grau-getigert, frisst nur B3.",
        "schläft auf dem sessel mit der decke.",
        "wenn der napf leer ist, wird sie laut. das ist",
        "die einzige stelle in dieser wohnung, an der",
        "noch jemand laut wird.",
      ],
    },
    {
      type: "file",
      name: "b3_bestand.txt",
      kind: "text",
      size: 360,
      date: "06.11.1997",
      content: [
        "── B3-vorrat, stand 06.11. ───────────────────",
        "",
        "  rind-äquivalent     2 dosen   (knapp)",
        "  fisch-äquivalent    0 dosen   (aus)",
        "  trockenfutter       1/4 packung",
        "",
        "anmerkung: nächste lieferung erst freitag.",
        "wenn ich nicht heute noch los, wird sie laut.",
        "und wenn lotti laut wird, wird der korridor laut.",
      ],
    },
    {
      type: "file",
      name: "stadtwerke_alt.txt",
      kind: "text",
      size: 540,
      date: "1991",
      content: [
        "── persönlicher auszug, mitgenommen 1991 ─────",
        "",
        "trägersignal 104,6 MHz — manuell nachregeln,",
        "alle 90 sekunden, schicht: 1 person.",
        "",
        "ich war diese person, von 1986 bis 1991.",
        "ich hab nie jemandem davon erzählt.",
        "vielleicht habe ich gerade jetzt jemandem",
        "davon erzählt. ich weiß nicht mehr genau,",
        "wer heute hier war.",
      ],
    },
    {
      type: "file",
      name: "todo.txt",
      kind: "text",
      size: 220,
      date: "—",
      content: [
        "  [ ] B3 nachholen (rind + fisch)",
        "  [ ] kratzbaum reparieren",
        "  [ ] decke waschen — oder nicht. lotti riecht",
        "      sich selbst gern.",
        "  [ ] das system irgendwann mal aktualisieren.",
        "      vielleicht. v2.0 läuft seit jahren stabil.",
      ],
    },
    {
      type: "file",
      name: ".alt_brief.txt",
      kind: "text",
      size: 420,
      date: "—",
      content: [
        "── nie abgeschickt ───────────────────────────",
        "",
        "liebe e.,",
        "",
        "es ist jetzt zwölf jahre her. ich glaube,",
        "ich erkenne deine handschrift nicht mehr,",
        "wenn sie käme. aber ich erkenne, dass keine",
        "kommt. das ist auch eine art handschrift.",
        "",
        "die katze ist gut. sie schläft viel.",
        "ich auch.",
        "",
        "                                          — b.",
      ],
    },
    {
      type: "file",
      name: ".freiheit.txt",
      kind: "text",
      size: 4200,
      date: "—",
      content: FREIHEIT_TXT,
    },
    {
      type: "file",
      name: ".layard.txt",
      kind: "text",
      size: 4400,
      date: "—",
      requires: "bodoLeftForB3",
      content: LAYARD_TXT,
    },
    {
      type: "file",
      name: ".forge.macro",
      kind: "text",
      size: 320,
      date: "—",
      content: [
        "# .forge.macro — interne werkstatt-vorlage",
        "# bodo, halbtags. wird vom befehl »forge« geladen.",
        "#",
        "# eingaben (im inventar erwartet):",
        "#   - quittungsbogen schicht b (blanko)",
        "#   - trockensiegel-abdruck (schicht a)",
        "#   - aushang 7.1 (original, mit kopfzeile)",
        "#   - eine schicht-b-gegenzeichnung (z.b. wartung)",
        "#",
        "# ausgabe: quittung 4317-k, fertig zum versand per rohrpost.",
        "# wer das hier liest: bitte nicht für blödsinn benutzen.",
        "#                                          — b.",
      ],
    },
    {
      type: "file",
      name: "heelsund.txt",
      kind: "text",
      size: 540,
      date: "—",
      content: [
        "── brief von zuhause, vor zwei wochen ────────",
        "",
        "lieber bodo,",
        "",
        "henning war am wochenende hier, das schiff",
        "lag drei tage im hafen. er hat gefragt,",
        "wann du mal wieder kommst. ich hab gesagt,",
        "der komplex lässt ihn nicht.",
        "",
        "die schwester sagt, mein knie wird nicht",
        "besser. ich sag, das knie ist 79, das darf.",
        "",
        "der wind hat den alten sendemast vom papa",
        "umgelegt. die küstenwache hat ihn nicht",
        "wieder aufgestellt. niemand braucht ihn mehr.",
        "",
        "ruf sonntag an, bodo. wie immer.",
        "",
        "                                       — mama",
      ],
    },
    {
      type: "file",
      name: "mieterliste.txt",
      kind: "text",
      size: 1180,
      date: "—",
      content: [
        "── mieterliste, hausmeister-notizen ──────────",
        "── nicht weitergeben. nicht in akte. ─────────",
        "",
        "2610  helka vint, ende 60.",
        "      ehemals zentralverwaltung, 41 jahre.",
        "      witwe (offiziell verlobt, nie verheiratet —",
        "      karsten, 2014, lunge). öffnet die tür nicht.",
        "      stört nie. zahlt pünktlich.",
        "",
        "2611  layard worag.",
        "      siehe extra-akte. nicht hier.",
        "",
        "2612  ich.",
        "",
        "2613  philippe marteau, anfang 40.",
        "      aktenschreiber E70. allein.",
        "      schweigt. seit 11 jahren noch nie",
        "      eine beschwerde, nie ein gespräch im",
        "      treppenhaus. mutter (E70-1812) ruft",
        "      manchmal nach ihm an. er geht nicht ran.",
        "",
        "2615  carrier-fall. siehe carrier-akte.",
        "      sanitäter informieren bei vorfall.",
        "",
        "4601  mira, 16. komplex-kind, hier geboren.",
        "      vater ilan (3804) — trafo-unfall 2021,",
        "      schacht 56. mutter yael lebt in E54.",
        "      onkel roald (4604) ist die bezugsperson.",
        "      flyer im korridor, nicht meine baustelle.",
        "",
        "4604  roald (vorname reicht).",
        "      vaters bruder von 4601. trinkt zu viel,",
        "      grüßt zu laut. harmlos.",
      ],
    },
  ],
};

const SYSTEM_DIR_BODO: FsDir = {
  type: "dir",
  name: "system",
  desc: "Konfigurationsdateien. Hausmeister-Konsole.",
  children: [
    {
      type: "file",
      name: "wartung.cfg",
      kind: "config",
      size: 220,
      date: "—",
      content: [
        "# wartung.cfg — Hausmeister-Profil 2/E67",
        "user        = bodo",
        "gid         = hausmeister",
        "block       = 26",
        "schicht     = halbtags (de facto: durchgehend)",
        "pager       = 4711",
      ],
    },
    {
      type: "file",
      name: "anleitungen_alt.txt",
      kind: "text",
      size: 410,
      date: "1991",
      content: [
        "── notiz für mich, falls ich's vergesse ──────",
        "",
        "trägersignal 104,6: nicht anfassen.",
        "aufzug E67/2:        bei sperrung 4711 prüfen.",
        "lüftung 5:           grenzwert ist NICHT alarm.",
        "",
        "wer mehr will, soll bei der zentral-it fragen.",
        "ich bin nur der hausmeister.",
      ],
    },
  ],
};

/** Unix-like root für Bodos Hausmeister-Maschine. */
export const FILESYSTEM_BODO: FsDir = {
  type: "dir",
  name: "",
  desc: "CentralOS Wurzelverzeichnis (Hausmeister)",
  children: [
    SYSTEM_DIR_BODO,
    {
      type: "dir",
      name: "home",
      desc: "Benutzerverzeichnisse.",
      children: [HOME_BODO],
    },
    {
      type: "dir",
      name: "etc",
      desc: "Systemkonfiguration.",
      children: [
        {
          type: "file",
          name: "hosts",
          kind: "config",
          size: 180,
          date: "—",
          content: [
            "# /etc/hosts — CentralOS",
            "127.0.0.1    localhost",
            "10.67.0.1    gateway.e67",
            "10.67.0.2    leitstelle.e67   # 001",
            "10.67.26.10  helka.e67        # 2610",
            "10.67.26.11  worag.e67        # 2611",
            "10.67.26.13  philippe.e67     # 2613",
            "10.67.26.14  ennis.e67        # 2614",
            "10.71.0.1    gateway.e71",
            "10.71.15.34  sprechzimmer.e71",
          ],
        },
        {
          type: "file",
          name: "passwd",
          kind: "config",
          size: 200,
          date: "—",
          content: [
            "# /etc/passwd — Auszug",
            "root:x:0:0:CentralOS:/root:/bin/sh",
            "bodo:x:2612:200:Marschke, B.:/home/bodo:/bin/sh",
            "leitstelle:x:1:1:Leitstelle 001:/var/leitstelle:/bin/false",
          ],
        },
        {
          type: "file",
          name: "motd",
          kind: "text",
          size: 240,
          date: "—",
          content: [
            "── CentralOS v2.0 ─────────────────────────────",
            "Hausmeister-Konsole 2/E67.",
            "Frequenz 104,6: NICHT anfassen.",
            "Bei Wartungs-Alarmen siehe »maint list«.",
            "Stadtwerke. Schicht: halbtags.",
          ],
        },
        {
          type: "file",
          name: "sektor.conf",
          kind: "config",
          size: 300,
          date: "—",
          content: [
            "# /etc/sektor.conf",
            "sektor        = E67",
            "korridor      = 26",
            "gateway       = E67/E71",
            "frequency     = 104.600 MHz",
            "quiet_hours   = none",
          ],
        },
        {
          type: "file",
          name: "fstab",
          kind: "config",
          size: 260,
          date: "—",
          content: [
            "# /etc/fstab — CentralOS",
            "# device           mount         type     opts",
            "/dev/sda1          /             ext2     ro,sync",
            "/dev/sda2          /home         ext2     rw",
            "/dev/carrier0      /var/carrier  pcmstrm  ro",
            "tmpfs              /tmp          tmpfs    rw,size=4M",
          ],
        },
        {
          type: "file",
          name: "resolv.conf",
          kind: "config",
          size: 120,
          date: "—",
          content: [
            "# /etc/resolv.conf",
            "nameserver  10.67.0.1",
            "nameserver  10.0.0.1",
            "search      e67.zentrale",
          ],
        },
        {
          type: "file",
          name: "issue",
          kind: "text",
          size: 90,
          date: "—",
          content: [
            "CentralOS v2.0 — Hausmeister-Konsole E67",
            "Login: \\u   TTY: \\l",
          ],
        },
        {
          type: "file",
          name: "shadow",
          kind: "config",
          size: 140,
          date: "—",
          content: [
            "── /etc/shadow ────────────────────────────────",
            "cat: shadow: Zugriff verweigert.",
          ],
        },
        {
          type: "file",
          name: "cron.tab",
          kind: "config",
          size: 220,
          date: "—",
          content: [
            "# /etc/cron.tab",
            "# m  h  dom mon dow  cmd",
            "0   *  *   *   *    /usr/bin/carrier-daemon --keepalive",
            "0   3  *   *   *    /usr/bin/centralos --rotate-logs",
            "*/15 *  *  *   *    /usr/bin/maint --pull",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "var",
      desc: "Variable Daten, Logs.",
      children: [
        {
          type: "dir",
          name: "log",
          desc: "Systemlogs.",
          children: [
            {
              type: "file",
              name: "maint.log",
              kind: "log",
              size: 540,
              date: "06.11.1997",
              content: [
                "── maint.log ──────────────────────────────────",
                "1997-11-06 09:42:00  Aufzug E67/2  GESPERRT (4711)",
                "1997-11-06 08:12:00  gateway E67/E71  ERROR 4567",
                "1997-11-04 12:08:00  Lüftung 5     grenzwertig",
                "1997-11-02 06:30:00  Routine      Tech-Knoten 5/6",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "auth.log",
              kind: "log",
              size: 380,
              date: "06.11.1997",
              content: [
                "── auth.log ───────────────────────────────────",
                "1997-11-06 06:14:00  login bodo         OK (lokal)",
                "1997-11-06 07:02:00  sudo  bodo         OK (maint)",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "kern.log",
              kind: "log",
              size: 540,
              date: "06.11.1997",
              content: [
                "── kern.log ───────────────────────────────────",
                "kernel: CentralOS 2.0 boot OK",
                "kernel: carrier0 attached at 104.600 MHz",
                "kernel: WARN /dev/null write throttled",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "dmesg",
              kind: "log",
              size: 380,
              date: "—",
              content: [
                "[    0.00] CentralOS v2.0 starting",
                "[    0.12] cpu0: 33 MHz (synthetisch)",
                "[    0.40] mem: 4096 KB",
                "[    1.10] carrier0: lock 104.600 MHz",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "mail",
          desc: "Postfächer.",
          children: [
            {
              type: "file",
              name: "bodo",
              kind: "mail",
              size: 80,
              date: "—",
              content: [
                "Mailbox-Verweis — siehe 'inbox' im Terminal.",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "spool",
          desc: "Spool-Verzeichnis.",
          children: [
            {
              type: "file",
              name: "cron.last",
              kind: "text",
              size: 80,
              date: "—",
              content: [
                "carrier-daemon  OK   06.11.1997 09:00",
                "maint           OK   06.11.1997 09:15",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "usr",
      desc: "Installierte Programme.",
      children: [
        {
          type: "dir",
          name: "bin",
          desc: "Ausführbare Dateien.",
          children: [
            {
              type: "file",
              name: "centralos",
              kind: "config",
              size: 65536,
              date: "—",
              content: ["[binary — 65536 Bytes]"],
            },
            {
              type: "file",
              name: "maint",
              kind: "config",
              size: 12288,
              date: "—",
              content: [
                "[binary — 12288 Bytes]",
                "Hausmeister-Werkzeug. Befehl: maint list / maint cancel <id>.",
              ],
            },
            {
              type: "file",
              name: "lotti",
              kind: "config",
              size: 4096,
              date: "—",
              content: [
                "[binary — 4096 Bytes]",
                "Privat. Fütterungskalender. Tippe: lotti",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "share",
          desc: "Gemeinsam genutzte Daten.",
          children: [
            {
              type: "file",
              name: "README",
              kind: "text",
              size: 200,
              date: "—",
              content: [
                "CentralOS v2.0 — Hausmeister-Konsole.",
                "Wartungswerkzeug: maint. Privat: lotti.",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "bin",
      desc: "Grundlegende Befehle.",
      children: [
        { type: "file", name: "sh",   kind: "config", size: 8192, date: "—", content: ["[binary]"] },
        { type: "file", name: "ls",   kind: "config", size: 2048, date: "—", content: ["[binary]"] },
        { type: "file", name: "cat",  kind: "config", size: 1920, date: "—", content: ["[binary]"] },
        { type: "file", name: "cd",   kind: "config", size: 1024, date: "—", content: ["[builtin]"] },
        { type: "file", name: "pwd",  kind: "config", size: 1024, date: "—", content: ["[binary]"] },
        { type: "file", name: "tree", kind: "config", size: 3840, date: "—", content: ["[binary]"] },
        { type: "file", name: "echo", kind: "config", size: 720,  date: "—", content: ["[binary]"] },
      ],
    },
    {
      type: "dir",
      name: "tmp",
      desc: "Flüchtige Daten.",
      children: [
        {
          type: "file",
          name: "scratch.txt",
          kind: "text",
          size: 180,
          date: "—",
          content: [
            "[notiz, vermutlich von gestern]",
            "- B3 nachholen",
            "- aufzug 4711 prüfen",
            "- lüftung 5 ggf. drücken",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "dev",
      desc: "Geräte.",
      children: [
        { type: "file", name: "null",     kind: "config", size: 0, date: "—", content: [""] },
        { type: "file", name: "carrier0", kind: "config", size: 0, date: "—", content: ["[device — Trägersignal 104.600 MHz, read-only]"] },
        { type: "file", name: "tty0",     kind: "config", size: 0, date: "—", content: ["[device — Terminal]"] },
      ],
    },
  ],
};

/** Resolve a path array (e.g. ['home','bodo']) starting from root. */
export function resolveBodo(parts: string[]): FsNode | null {
  let node: FsNode = FILESYSTEM_BODO;
  for (const p of parts) {
    if (node.type !== "dir") return null;
    const child: FsNode | undefined = node.children.find((c) => c.name === p);
    if (!child) return null;
    node = child;
  }
  return node;
}

export function pathStringBodo(parts: string[]): string {
  return "/" + parts.join("/");
}
