/**
 * Layards (Worag) Filesystem — eigenständiger Baum.
 *
 * Vollständig getrennt von Bodos Baum (filesystemBodo.ts). /home enthält
 * NUR /home/worag — Bodos Home liegt nicht hier und ist nur über
 * `telnet bodo.e67` erreichbar. Änderungen in dieser Datei haben keine
 * Auswirkung auf Bodos Terminal.
 */

export interface FsFile {
  type: "file";
  name: string;
  kind?: "text" | "log" | "image" | "news" | "mail" | "audio" | "config";
  size?: number;
  date?: string;
  /** Optional StoryFlag required to reveal this file. */
  requires?: string;
  content: string[];
}

export interface FsDir {
  type: "dir";
  name: string;
  desc?: string;
  children: FsNode[];
}

export type FsNode = FsFile | FsDir;

export const HOME_PATH_WORAG: string[] = ["home", "layard"];

const HOME_WORAG: FsDir = {
  type: "dir",
  name: "layard",
  desc: "Persönliches Verzeichnis — Worag, L.",
  children: [
    {
      type: "file",
      name: "adventure.bin",
      kind: "config",
      size: 4096,
      date: "21.08.1996",
      content: [
        "[ausführbare Datei — 4096 Bytes]",
        "",
        "Dies ist ein Programm. Tippe ins Terminal:",
        "    adventure",
        "oder:",
        "    ./adventure.bin",
        "um es zu starten.",
        "",
        "── HEADER ────────────────────────────────────────",
        "Titel:  »Ein Tag draußen«",
        "Autor:  L. Worag, Zimmer 2611",
        "Notiz:  Geschrieben in 14 Nachtschichten zwischen",
        "        dem 7. August und 21. August 1996.",
        "        Setting: Berlin, ca. 2026.",
        "        Quelle: was übrig war.",
        "── Ende ──────────────────────────────────────────",
      ],
    },
    {
      type: "dir",
      name: "tagebuch",
      desc: "Private Einträge. Verschlüsselt — Schicht 0.",
      children: [
        {
          type: "file",
          name: "1986-09-12.txt",
          kind: "text",
          size: 2148,
          date: "12.09.1986",
          content: [
            "── Eintrag, 12. September 1986 ─────────────────",
            "",
            "Heute wurde ich zugewiesen. Quadrant E67, Zimmer 2611.",
            "Sie haben mir gesagt, das sei vorübergehend. Drei Monate,",
            "vielleicht ein halbes Jahr, bis sich die Lage »stabilisiert«.",
            "",
            "Insa hat mich zum Aufzug begleitet. Sie hat mir den",
            "kleinen Empfänger gegeben — graues Plastik, ein Knopf,",
            "ein Drehrad. »Sender 104.6«, hat sie gesagt.",
            "»Lass es immer leise laufen. Du gewöhnst dich daran.",
            "Du wirst es nicht mehr ausschalten wollen.«",
            "",
            "Sie hatte recht.",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1989-04-03.txt",
          kind: "text",
          size: 1894,
          date: "03.04.1989",
          content: [
            "── Eintrag, 3. April 1989 ─────────────────────",
            "",
            "Drei Jahre. Niemand hat mehr »vorübergehend« gesagt.",
            "",
            "Mein Nachbar — Philippe, zwei Türen weiter — hat",
            "angefangen, gegen die Wand zu schlagen, wenn das",
            "Radio ausfällt. Heute Morgen war es zwölf Minuten",
            "still. Ich habe seine Faust durch zwei Wände gehört.",
            "",
            "Als der Träger zurückkam, hat er aufgehört. Sofort.",
            "Wie ein Hund, dem man den Napf hinstellt.",
            "",
            "Ich frage mich, wie ich aussehe, wenn es bei mir aussetzt.",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1993-11-30.txt",
          kind: "text",
          size: 1620,
          date: "30.11.1993",
          content: [
            "── Eintrag, 30. November 1993 ─────────────────",
            "",
            "Sieben Jahre. Ich habe heute zum ersten Mal über",
            "die Frequenz nachgedacht — nicht über das, was sie",
            "spielt, sondern darüber, was sie ist.",
            "",
            "Sinusförmig, würde ich sagen. Aber zu sauber für",
            "Musik. Und der Bass, der nicht da sein sollte —",
            "ich höre ihn in den Zähnen, bevor ich ihn im Ohr höre.",
            "",
            "Wenn das ein Trägersignal ist: Was wird getragen?",
            "Und in welche Richtung?",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1996-12-24.txt",
          kind: "text",
          size: 1102,
          date: "24.12.1996",
          content: [
            "── Eintrag, 24. Dezember 1996 ─────────────────",
            "",
            "Ich habe heute versucht, das Radio auszuschalten.",
            "Eine Sekunde. Mehr nicht.",
            "",
            "Ich kann es nicht beschreiben. Es war, als würde",
            "jemand mit einem Messer die Innenseite meines",
            "Schädels ausschaben. Insa hat mich angerufen, drei",
            "Minuten später. Sie hat nichts gesagt. Sie hat nur",
            "gewartet, bis ich es wieder eingeschaltet habe.",
            "",
            "Sie wusste es. Bevor ich es selbst gewusst habe.",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1997-11-05.txt",
          kind: "text",
          size: 980,
          date: "05.11.1997",
          content: [
            "── Eintrag, 5. November 1997 ──────────────────",
            "",
            "Morgen ist Wartung. Insa hat angedeutet, dass",
            "etwas geschehen wird. Sie hat es nicht gesagt,",
            "aber sie hat zweimal das Wort »Verantwortung«",
            "fallen lassen. Bei ihr heißt das immer dasselbe.",
            "",
            "Ich bin bereit. Glaube ich.",
            "── Ende ────────────────────────────────────────",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "gedanken",
      desc: "Lose Notizen. Nicht sortiert.",
      children: [
        {
          type: "file",
          name: "resonanz.md",
          kind: "text",
          size: 612,
          date: "—",
          content: [
            "# Resonanz",
            "",
            "Resonanz ist, wenn ein Körper einen anderen zum",
            "Schwingen bringt, ohne ihn zu berühren. Nur über",
            "die Luft. Nur über die richtige Frequenz.",
            "",
            "Frage: Wenn 104.6 mich zum Schwingen bringt —",
            "wer ist der andere Körper?",
            "",
            "Antwort: Vielleicht nicht ein Körper. Vielleicht",
            "ein Gebäude. Vielleicht der ganze Sektor.",
          ],
        },
        {
          type: "file",
          name: "stille.md",
          kind: "text",
          size: 384,
          date: "—",
          content: [
            "# Stille",
            "",
            "Ich kann mich nicht erinnern, wie Stille klingt.",
            "Das ist kein Bild. Das ist eine Aussage.",
            "",
            "Ich habe es einmal versucht aufzuschreiben:",
            "»Stille ist ___.«",
            "Die Lücke ist seit elf Jahren leer.",
          ],
        },
        {
          type: "file",
          name: "philippe.md",
          kind: "text",
          size: 540,
          date: "—",
          requires: "metPhilippe",
          content: [
            "# Philippe",
            "",
            "Er denkt, er sei mein Freund. Er ist es nicht.",
            "Er ist die Wand, gegen die ich schaue, wenn ich",
            "nicht in den Spiegel sehen will.",
            "",
            "Wenn ich ihn schreien höre, weiß ich, dass mein",
            "Empfänger noch funktioniert. Das ist die einzige",
            "Funktion, die er für mich erfüllt.",
            "",
            "Trotzdem: Wenn er stirbt, will ich daneben stehen.",
          ],
        },
        {
          type: "file",
          name: ".einsamkeit.md",
          kind: "text",
          size: 720,
          date: "—",
          content: [
            "# Einsamkeit",
            "",
            "Es ist nicht so, dass niemand da wäre. Insa ruft an.",
            "Philippe schreit durch zwei Wände. Im Korridor laufen",
            "Schritte, die nicht meine sind.",
            "",
            "Es ist eher: Niemand kennt das Wort, das ich am",
            "häufigsten denke. Ich kenne es selbst kaum noch.",
            "Ich habe es so lange nicht gesagt, dass ich nicht",
            "weiß, ob es noch dasselbe Wort wäre.",
            "",
            "Wenn jemand käme — wirklich käme, nicht nur an die",
            "Tür klopfte —, ich glaube, ich würde nicht öffnen.",
            "Aus Angst, er sieht, was hier nicht mehr ist.",
          ],
        },
        {
          type: "file",
          name: ".koerper.md",
          kind: "text",
          size: 680,
          date: "—",
          content: [
            "# Körper",
            "",
            "Es gab eine Zeit, da war das eine Frage. Ob Männer.",
            "Ob Frauen. Ob beides. Ob etwas dazwischen, das im",
            "Lehrbuch nicht vorkam.",
            "",
            "Hier kommt es im Lehrbuch nicht vor, weil es kein",
            "Lehrbuch mehr gibt. Und weil keiner mehr fragt.",
            "",
            "Manchmal träume ich von einer Hand, die nicht meine",
            "ist. Ich kann das Geschlecht der Hand nicht sagen.",
            "Ich glaube, das ist die ehrlichste Antwort, die ich",
            "je auf diese Frage hatte.",
            "",
            "Im Sektor wird geschwiegen. Ich schweige mit.",
            "Aber das Schweigen ist nicht dasselbe wie nichts.",
          ],
        },
        {
          type: "file",
          name: ".freiheit.md",
          kind: "text",
          size: 860,
          date: "—",
          content: [
            "# Freiheit",
            "",
            "Manchmal denke ich: Was, wenn die Türen offen wären?",
            "Nicht nur die Sektor-Tür. Alle. Wenn jeder gehen",
            "könnte, wohin er wollte. Wenn 104,6 nur ein Sender",
            "unter vielen wäre, den man wegdrehen darf.",
            "",
            "Ich glaube, die meisten würden trotzdem bleiben.",
            "Nicht aus Liebe. Aus Gewohnheit. Aus Angst vor dem",
            "Geräusch, das die eigene Stimme macht, wenn niemand",
            "antwortet.",
            "",
            "Und ich frage mich: Wäre es dann noch Freiheit?",
            "Oder nur eine andere Form der Stille?",
            "",
            "Vielleicht ist Freiheit das, was zwischen zwei",
            "Menschen entsteht, die sich beide trauen, etwas zu",
            "wollen. Davon habe ich hier noch keinen gesehen.",
            "Aber ich höre es manchmal — durch die Wand, in",
            "Philippes Schreien. Etwas Lebendiges, das nicht",
            "weiß, dass es eingesperrt ist.",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "bilder",
      desc: "ASCII-Archiv. Bilder werden im Sektor nicht mehr gedruckt.",
      children: [
        {
          type: "file",
          name: "fenster.ascii",
          kind: "image",
          size: 410,
          date: "1991",
          content: [
            "  ┌──────────────────────────┐",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  └──────────────────────────┘",
            "",
            "Bildtitel: »Fenster, Zimmer 2611«",
            "Aufgenommen: 14.07.1991",
            "Notiz: Beton, grau. Es gibt kein Glas.",
          ],
        },
        {
          type: "file",
          name: "insa.ascii",
          kind: "image",
          size: 720,
          date: "1986",
          content: [
            "        .--‾‾--.",
            "       /  o  o  \\",
            "      |    ><    |",
            "      |  \\____/  |",
            "       \\        /",
            "        ‘------’",
            "",
            "Bildtitel: »I. B. — Leitstelle, erster Tag«",
            "Datum: 12.09.1986",
            "Notiz: Sie hat damals noch gelächelt.",
          ],
        },
        {
          type: "file",
          name: "korridor.ascii",
          kind: "image",
          size: 690,
          date: "1995",
          content: [
            "  ╔══════════════════════════╗",
            "  ║  ▓▓                  ▓▓  ║",
            "  ║  ▓▓   ─── ─── ───    ▓▓  ║",
            "  ║  ▓▓                  ▓▓  ║",
            "  ║  ▓▓ [2611]    [2613] ▓▓  ║",
            "  ║  ▓▓                  ▓▓  ║",
            "  ║  ▓▓ ░░░░░░░░░░░░░░░░ ▓▓  ║",
            "  ╚══════════════════════════╝",
            "",
            "Bildtitel: »Korridor 26, abends«",
            "Notiz: Die Lampen flackern im Takt von 104.6.",
          ],
        },
        {
          type: "file",
          name: "vater.ascii",
          kind: "image",
          size: 510,
          date: "1984",
          requires: "metMikael",
          content: [
            "       ___",
            "      /   \\",
            "     | o o |",
            "     |  ─  |",
            "     |\\___/|",
            "    /|     |\\",
            "",
            "Bildtitel: »M. B. — vor der Zuweisung«",
            "Datum: 02.02.1984",
            "Notiz: Insas Vater. Bevor er nach E71 ging.",
            "Er hat dieses Foto in seiner Westentasche.",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "presse",
      desc: "Zeitungsausschnitte. Aus der Zentral-Datenbank kopiert.",
      children: [
        {
          type: "file",
          name: "1985_freie-presse.txt",
          kind: "news",
          size: 1820,
          date: "23.05.1985",
          content: [
            "── DIE FREIE PRESSE — 23. Mai 1985 ────────────",
            "Seite 3, Lokales",
            "",
            "       SEKTOR E67 GEHT IN BETRIEB",
            "",
            "Nach achtzehn Monaten Bauzeit wurde gestern der",
            "Wohnsektor E67 an das städtische Versorgungsnetz",
            "angeschlossen. Insgesamt 4.612 Wohnungen sollen",
            "Familien aufnehmen, die im Zuge der Stadtkern-",
            "verdichtung umgesiedelt werden.",
            "",
            "»Eine Lösung für eine ganze Generation«,",
            "kommentierte ein Sprecher der Stadtwerke.",
            "",
            "Über das in der Sektorzentrale installierte",
            "Funksystem — Frequenz 104.6 MHz — sollen die",
            "Bewohner mit Informationen versorgt werden.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1986_freie-presse.txt",
          kind: "news",
          size: 1980,
          date: "14.11.1986",
          content: [
            "── DIE FREIE PRESSE — 14. November 1986 ───────",
            "Seite 4, Lokales",
            "",
            "  ANWOHNER FORDERN ZUGANGSCODE FÜR SEKTOR E67",
            "",
            "Auf einer öffentlichen Versammlung im Foyer von",
            "Block 26 haben sich am Mittwochabend nach Anga-",
            "ben der Versammlungsleitung 312 Bewohnerinnen",
            "und Bewohner einstimmig dafür ausgesprochen,",
            "die offenen Sektor-Türen zu E71 mit einer",
            "elektronischen Code-Sperre zu versehen.",
            "",
            "Auslöser sind drei Vorfälle der vergangenen",
            "Wochen, bei denen »fremde Personen« — vermutlich",
            "aus dem unsanierten Sektor E71 — durch die",
            "Korridore von E67 gestreift sein sollen. Verletzt",
            "wurde niemand. »Aber das Gefühl«, so eine",
            "Sprecherin der Initiative »Sicheres E67«, »ist",
            "ein anderes geworden.«",
            "",
            "Die Stadtwerke haben angekündigt, dem Wunsch zu",
            "entsprechen, sobald die nötige Hardware verfüg-",
            "bar sei. Die Verwaltung des Codes solle über",
            "die Sektor-Leitstelle erfolgen.",
            "",
            "Eine Minderheit warnte vor »unnötigen Schran-",
            "ken«. Ihr Antrag, stattdessen einen Sicherheits-",
            "dienst einzurichten, fand keine Mehrheit.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1988_morgenblatt.txt",
          kind: "news",
          size: 1430,
          date: "07.10.1988",
          content: [
            "── MORGENBLATT — 7. Oktober 1988 ──────────────",
            "Seite 7, Vermischtes",
            "",
            "    KLAGEN ÜBER OHRENSCHMERZEN IN E67",
            "",
            "Bewohner des Sektors E67 berichten zunehmend",
            "über Druckgefühl und »inneres Brummen«. Der",
            "ärztliche Dienst der Stadt verweist auf den",
            "noch jungen Bau und die ungewohnte Akustik der",
            "Betonkorridore.",
            "",
            "Ein Zusammenhang mit dem sektoreigenen Funkkanal",
            "104.6 sei »technisch ausgeschlossen«, so die",
            "Stadtwerke. Eine Untersuchung wurde abgelehnt.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1989_buergerblatt.txt",
          kind: "news",
          size: 1740,
          date: "02.04.1989",
          content: [
            "── BÜRGERBLATT E67 — 2. April 1989 ────────────",
            "Sonderausgabe Block 26",
            "",
            "    PETITION: »MELDEN, WENN MAN DAS HAUS",
            "     VERLÄSST« — 2.847 UNTERSCHRIFTEN",
            "",
            "Eine von Frau I. Bauerfeind (Leitstelle) und",
            "Herrn G. Marschke (Hausmeister Block 26) initi-",
            "ierte Petition fordert die verbindliche elektro-",
            "nische Ausgangsmeldung für alle Bewohnerinnen",
            "und Bewohner des Sektors.",
            "",
            "Hintergrund sind zwei seit dem Vorjahr unauf-",
            "geklärte Vermisstenfälle. »Wenn man weiß, wer",
            "draußen ist, weiß man auch, wem etwas zugesto-",
            "ßen sein könnte«, heißt es im Begründungstext.",
            "",
            "Innerhalb von neun Tagen unterzeichneten 2.847",
            "der 4.612 Haushalte. Die Stadtwerke haben zuge-",
            "sagt, einen entsprechenden Befehl (»report exit«)",
            "im nächsten CentralOS-Update bereitzustellen.",
            "",
            "Stimmen aus der Bewohnerschaft:",
            "»Endlich sieht jemand hin.« — H. K., 2418",
            "»Hätte man früher haben können.« — F. T., 2705",
            "»Wer nichts zu verbergen hat …« — anonym, 2611",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1991_abendkurier.txt",
          kind: "news",
          size: 1690,
          date: "29.03.1991",
          content: [
            "── ABENDKURIER — 29. März 1991 ────────────────",
            "Seite 1, Aufmacher",
            "",
            "       UNFALL IM SEKTOR E71 — DREI TOTE",
            "",
            "Bei einem nicht näher benannten Zwischenfall im",
            "Versorgungsschacht 14 des Sektors E71 sind in",
            "der Nacht zum Donnerstag drei Techniker ums",
            "Leben gekommen. Die Stadtwerke sprechen von",
            "einem »akustischen Resonanzereignis«.",
            "",
            "Augenzeugen berichten, dass die Männer »wie auf",
            "Befehl« stehen geblieben seien, kurz bevor der",
            "Schacht einstürzte. Ein Sprecher dementierte",
            "Berichte, wonach die sektoreigene Frequenz an-",
            "gehoben worden sei.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1992_stadtanzeiger.txt",
          kind: "news",
          size: 1620,
          date: "18.08.1992",
          content: [
            "── STADTANZEIGER — 18. August 1992 ────────────",
            "Seite 6, Lokales",
            "",
            "  E67-BEIRAT LOBT »FREIWILLIGE WARTUNGSFENSTER«",
            "",
            "Der Bewohnerbeirat des Sektors E67 hat in seiner",
            "gestrigen Sitzung das städtische Konzept der",
            "»freiwilligen Wartungsfenster« ausdrücklich",
            "begrüßt und eine Ausweitung beantragt.",
            "",
            "Während dieser Fenster ist das ZENTRAL.NETZ",
            "regelmäßig nicht erreichbar; der Sektor bleibt",
            "in dieser Zeit auf den eigenen Notbetrieb (104.6)",
            "angewiesen. »Wir spüren erst dann, wie gut es",
            "uns sonst geht«, kommentierte ein Beiratsmit-",
            "glied. Eine Verlängerung von derzeit zwei auf",
            "acht Wartungstage pro Monat sei wünschenswert.",
            "",
            "Aus der Verwaltung war zu hören, der Beirat",
            "habe sich in den letzten zwei Jahren mehrfach",
            "für die Maßnahme stark gemacht. Eine entspre-",
            "chende Aufstockung sei »in Prüfung«.",
            "",
            "Kritische Stimmen, die auf die häufigen Aus-",
            "fallzeiten verwiesen, bezeichnete der Beirat",
            "als »destruktiv«.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1994_stadtanzeiger.txt",
          kind: "news",
          size: 1280,
          date: "11.06.1994",
          content: [
            "── STADTANZEIGER — 11. Juni 1994 ──────────────",
            "Seite 5, Politik",
            "",
            "  STADT ÜBERTRÄGT FUNKLIZENZEN AN »LEITSTELLE«",
            "",
            "Die städtische Funklizenz für die Frequenz",
            "104.6 wurde gestern offiziell an die neu",
            "gegründete »Leitstelle für Sektorale Versorgung«",
            "übergeben. Über die genaue Trägerschaft der",
            "Leitstelle liegen widersprüchliche Angaben vor.",
            "",
            "Anfragen unserer Redaktion blieben unbeantwortet.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1996_leserbrief.txt",
          kind: "news",
          size: 1490,
          date: "07.02.1996",
          content: [
            "── ABENDKURIER — 7. Februar 1996 ──────────────",
            "Leserbriefe, Seite 11",
            "",
            "        »WIR SIND DIE LAUTSPRECHER«",
            "",
            "Sehr geehrte Redaktion,",
            "",
            "ich möchte all jenen widersprechen, die unseren",
            "Sektor-Kanal 104.6 als »belastend« bezeichnen.",
            "Die Frequenz ist nicht das Problem — wir sind",
            "es. Wer abends die Engel-Trauer hört und sich",
            "anschließend leerer fühlt, hat einfach zu wenig",
            "selbst eingespeist.",
            "",
            "Mein Mann und ich nehmen seit drei Jahren an",
            "den freiwilligen Resonanz-Abenden in der Foyer-",
            "kapelle teil. Man legt die Hand an die Wand, man",
            "atmet, man lässt los. Wer regelmäßig dabei ist,",
            "weiß: 104.6 gibt nur zurück, was wir hineinlegen.",
            "Wir sind die Lautsprecher dieses Senders.",
            "",
            "Ich verstehe nicht, warum die Stadtwerke noch",
            "immer zögern, die Sendezeiten zu verlängern.",
            "Die Initiative »Mehr Mitstrahlen« sammelt dafür",
            "Unterschriften — bitte unterzeichnen Sie auch.",
            "",
            "Mit besten Grüßen",
            "C. Wennewitz, Block 24, Zimmer 2418",
            "── Ende des Leserbriefs ──────────────────────",
          ],
        },
        {
          type: "file",
          name: "1997_REDAKTIONSNOTIZ.txt",
          kind: "news",
          size: 760,
          date: "01.11.1997",
          requires: "heardMikaelTruth",
          content: [
            "── INTERNE REDAKTIONSNOTIZ — 1. Nov. 1997 ─────",
            "NICHT ZUR VERÖFFENTLICHUNG",
            "",
            "Quelle (anonym, ehem. Techniker E71) bestätigt:",
            "Der »Pain-Channel« auf 104.6 ist KEIN Sender,",
            "sondern eine Schleife. Die Hörer sind zugleich",
            "die Sender. Was über die Träger-Resonanz zurück-",
            "gespiegelt wird, dient der Leitstelle zur",
            "Lokalisierung und Verhaltensanalyse.",
            "",
            "Empfehlung: Story zurückhalten. Quellenschutz.",
            "── Ende ──────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: ".bewohnerbrief_1986.txt",
          kind: "news",
          size: 2240,
          date: "21.10.1986",
          requires: "heardMikaelTruth",
          content: [
            "── ABSCHRIFT — Original im Stadtarchiv ────────",
            "Eingang Stadtwerke: 21. Oktober 1986, Az. E67/86-441",
            "",
            "Sehr geehrte Damen und Herren der Verwaltung,",
            "",
            "wir, die unterzeichnenden Bewohnerinnen und",
            "Bewohner des Sektors E67, fordern Sie hiermit",
            "AUSDRÜCKLICH und EINSTIMMIG dazu auf:",
            "",
            "  1. die Sektor-Türen zu E71 unverzüglich mit",
            "     einer elektronischen Code-Sperre zu ver-",
            "     sehen, deren Code nur über die Leitstelle",
            "     erfragt werden kann;",
            "",
            "  2. eine verbindliche elektronische Ausgangs-",
            "     meldung für jeden Bewohner einzuführen;",
            "",
            "  3. den Sektor-eigenen Funkkanal 104.6 dauer-",
            "     haft zu betreiben, auch nachts, da viele",
            "     von uns ohne ihn nicht mehr einschlafen",
            "     können.",
            "",
            "Wir sind uns bewusst, dass diese Maßnahmen",
            "Einschränkungen mit sich bringen. Wir tragen",
            "diese Einschränkungen GERNE, weil sie uns das",
            "Gefühl geben, gesehen und versorgt zu werden.",
            "",
            "Es ist uns lieber, zu viel verwaltet zu werden,",
            "als noch eine Nacht ohne Antwort an der Wand",
            "zu liegen.",
            "",
            "Mit hochachtungsvollen Grüßen,",
            "der Bewohnerbeirat E67",
            "",
            "  Vorsitz:    G. Marschke (2612, Block 26)",
            "  Schrift:    I. Bauerfeind (2104, Block 21)",
            "  Beisitz:    C. Wennewitz (2418, Block 24)",
            "              H. Kamenev   (2503, Block 25)",
            "              F. Tessmer   (2705, Block 27)",
            "",
            "Anlage: 2.611 Unterschriften (4 Hefter, lose).",
            "",
            "  ── handschriftlicher Vermerk Stadtwerke ──",
            "  »antrag wird vollumfänglich entsprochen.",
            "   bewohner haben es sich so gewünscht.«",
            "  paraphe unleserlich, 24.10.1986",
            "── Ende der Abschrift ────────────────────────",
          ],
        },
      ],
    },
  ],
};

/** Where the terminal starts ("cd ~" returns here). */

const SYSTEM_DIR_WORAG: FsDir = {
  type: "dir",
  name: "system",
  desc: "Konfigurationsdateien. Ändern auf eigene Gefahr.",
  children: [
    {
      type: "file",
      name: "carrier.cfg",
      kind: "config",
      size: 290,
      date: "—",
      content: [
        "# carrier.cfg — Trägerkonfiguration Quadrant E67",
        "frequency      = 104.600 MHz",
        "modulation     = AM-RES (proprietär)",
        "duty_cycle     = 100%",
        "user_shutdown  = DENY",
        "leitstelle     = 001",
        "feedback_loop  = ENABLED   # siehe HANDBUCH §14",
      ],
    },
    {
      type: "file",
      name: "handbuch_p14.txt",
      kind: "config",
      size: 540,
      date: "—",
      content: [
        "── HANDBUCH §14 — Feedback-Schleife ───────────",
        "",
        "Die Trägerfrequenz 104.6 ist als bidirektionale",
        "Resonanzschleife ausgelegt. Empfänger im Sektor",
        "fungieren als passive Sender. Eine vollständige",
        "Abschaltung ist auf Bewohnerseite nicht vorgesehen.",
        "",
        "Bei Versuch der Abschaltung wird automatisch",
        "ein Eskalationsprotokoll an Leitstelle 001",
        "ausgelöst.",
        "",
        "[Abschnitt überarbeitet: 11/1997]",
        "── Ende ──────────────────────────────────────",
      ],
    },
    {
      type: "file",
      name: ".hidden_log",
      kind: "log",
      size: 1100,
      date: "—",
      requires: "calledLeitstelle",
      content: [
        "── audit.log [Auszug, automatisch generiert] ──",
        "",
        "1997-11-06 09:14:02  USER layard KEYPRESS volume--",
        "1997-11-06 09:14:03  ALERT carrier-attenuation",
        "1997-11-06 09:14:03  AUTODIAL leitstelle/001",
        "1997-11-06 09:14:11  CALL ANSWERED [BAUERFEIND, I.]",
        "1997-11-06 09:14:42  USER layard RESTORE volume",
        "1997-11-06 09:14:42  ALERT cleared",
        "",
        "── Hinweis: Eintrag wird in 30 Tagen rotiert. ──",
      ],
    },
  ],
};

/** Unix-like root für Layards Maschine. Player startet in /home/worag. */
export const FILESYSTEM_WORAG: FsDir = {
  type: "dir",
  name: "",
  desc: "CentralOS Wurzelverzeichnis",
  children: [
    SYSTEM_DIR_WORAG,
    {
      type: "dir",
      name: "home",
      desc: "Benutzerverzeichnisse.",
      children: [HOME_WORAG],
    },
    {
      type: "dir",
      name: "etc",
      desc: "Systemkonfiguration.",
      children: [
        {
          type: "file",
          name: "hosts",
          kind: "config",
          size: 180,
          date: "—",
          content: [
            "# /etc/hosts — CentralOS",
            "127.0.0.1    localhost",
            "10.67.0.1    gateway.e67",
            "10.67.0.2    leitstelle.e67   # 001",
            "10.67.26.10  helka.e67        # 2610",
            "10.67.26.12  bodo.e67         # 2612",
            "10.67.26.13  philippe.e67     # 2613",
            "10.67.26.14  ennis.e67        # 2614",
            "10.71.0.1    gateway.e71",
            "10.71.15.34  sprechzimmer.e71",
          ],
        },
        {
          type: "file",
          name: "passwd",
          kind: "config",
          size: 210,
          date: "—",
          content: [
            "# /etc/passwd — Auszug",
            "root:x:0:0:CentralOS:/root:/bin/sh",
            "layard:x:2611:100:Worag, L.:/home/layard:/bin/sh",
            "leitstelle:x:1:1:Leitstelle 001:/var/leitstelle:/bin/false",
          ],
        },
        {
          type: "file",
          name: "motd",
          kind: "text",
          size: 240,
          date: "—",
          content: [
            "── CentralOS v2.3 ─────────────────────────────",
            "Willkommen, Bewohner.",
            "Respektieren Sie die Sektorordnung.",
            "Frequenz 104,6 ist verpflichtend.",
            "Störungen: 001.",
          ],
        },
        {
          type: "file",
          name: "sektor.conf",
          kind: "config",
          size: 300,
          date: "—",
          content: [
            "# /etc/sektor.conf",
            "sektor        = E67",
            "korridor      = 26",
            "gateway       = E67/E71",
            "frequency     = 104.600 MHz",
            "quiet_hours   = none",
          ],
        },
        {
          type: "file",
          name: "fstab",
          kind: "config",
          size: 260,
          date: "—",
          content: [
            "# /etc/fstab — CentralOS",
            "# device           mount         type     opts",
            "/dev/sda1          /             ext2     ro,sync",
            "/dev/sda2          /home         ext2     rw",
            "/dev/carrier0      /var/carrier  pcmstrm  ro",
            "tmpfs              /tmp          tmpfs    rw,size=4M",
          ],
        },
        {
          type: "file",
          name: "resolv.conf",
          kind: "config",
          size: 120,
          date: "—",
          content: [
            "# /etc/resolv.conf",
            "nameserver  10.67.0.1",
            "nameserver  10.0.0.1",
            "search      e67.zentrale",
          ],
        },
        {
          type: "file",
          name: "issue",
          kind: "text",
          size: 90,
          date: "—",
          content: [
            "CentralOS v2.3 — Quadrant E67",
            "Login: \\u   TTY: \\l",
          ],
        },
        {
          type: "file",
          name: "shadow",
          kind: "config",
          size: 140,
          date: "—",
          content: [
            "── /etc/shadow ────────────────────────────────",
            "cat: shadow: Zugriff verweigert.",
          ],
        },
        {
          type: "file",
          name: "cron.tab",
          kind: "config",
          size: 220,
          date: "—",
          content: [
            "# /etc/cron.tab",
            "# m  h  dom mon dow  cmd",
            "0   *  *   *   *    /usr/bin/carrier-daemon --keepalive",
            "0   3  *   *   *    /usr/bin/centralos --rotate-logs",
            "*/5 *  *   *   *    /opt/leitstelle-tools/trace --ping",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "var",
      desc: "Variable Daten, Logs.",
      children: [
        {
          type: "dir",
          name: "log",
          desc: "Systemlogs.",
          children: [
            {
              type: "file",
              name: "carrier.log",
              kind: "log",
              size: 820,
              date: "06.11.1997",
              content: [
                "── carrier.log ────────────────────────────────",
                "1997-11-06 06:00:00  carrier UP    104.600 MHz",
                "1997-11-06 06:00:01  duty_cycle    100%",
                "1997-11-06 09:14:02  user layard   volume--",
                "1997-11-06 09:14:03  carrier       attenuation",
                "1997-11-06 09:14:11  leitstelle    ACK",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "gateway.log",
              kind: "log",
              size: 420,
              date: "06.11.1997",
              content: [
                "── gateway.log ────────────────────────────────",
                "1997-11-06 08:12:00  gateway E67/E71  ERROR 4567",
                "1997-11-06 08:12:00  reason           maintenance",
                "1997-11-06 08:12:00  manual_code      REQUIRED",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "auth.log",
              kind: "log",
              size: 980,
              date: "06.11.1997",
              content: [
                "── auth.log ───────────────────────────────────",
                "1997-11-06 05:58:11  login layard       OK",
                "1997-11-06 06:02:44  sudo  layard       DENIED",
                "1997-11-06 07:21:09  login leitstelle   OK (remote)",
                "1997-11-06 07:21:11  cmd   leitstelle   tail /var/log/carrier.log",
                "1997-11-06 09:14:11  call  leitstelle/001  ANSWERED",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "kern.log",
              kind: "log",
              size: 540,
              date: "06.11.1997",
              content: [
                "── kern.log ───────────────────────────────────",
                "kernel: CentralOS 2.3 boot OK",
                "kernel: carrier0 attached at 104.600 MHz",
                "kernel: radio0 attached (rx-only)",
                "kernel: WARN /dev/null write throttled",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "dmesg",
              kind: "log",
              size: 380,
              date: "—",
              content: [
                "[    0.00] CentralOS v2.3 starting",
                "[    0.12] cpu0: 33 MHz (synthetisch)",
                "[    0.40] mem: 4096 KB",
                "[    1.10] carrier0: lock 104.600 MHz",
                "[    1.11] resonance feedback loop ENABLED",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "mail",
          desc: "Postfächer.",
          children: [
            {
              type: "file",
                  name: "layard",
              kind: "mail",
              size: 80,
              date: "—",
              content: [
                "Mailbox-Verweis — siehe 'inbox' im Terminal.",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "leitstelle",
          desc: "Leitstelle 001 — Zugriff verweigert.",
          children: [
            {
              type: "file",
              name: ".locked",
              kind: "text",
              size: 60,
              date: "—",
              content: ["Zugriff verweigert. Kontakt: 001."],
            },
          ],
        },
        {
          type: "dir",
          name: "spool",
          desc: "Spool-Verzeichnis.",
          children: [
            {
              type: "file",
              name: "cron.last",
              kind: "text",
              size: 80,
              date: "—",
              content: [
                "carrier-daemon  OK   06.11.1997 09:00",
                "centralos       OK   06.11.1997 03:00",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "carrier",
          desc: "Trägersignal-Aufzeichnungen.",
          children: [
            {
              type: "file",
              name: "rec.1997-11-06.bin",
              kind: "config",
              size: 524288,
              date: "06.11.1997",
              content: [
                "[binary — 524288 Bytes]",
                "Aufzeichnung Trägersignal 104.600 MHz, 6h.",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "usr",
      desc: "Installierte Programme.",
      children: [
        {
          type: "dir",
          name: "bin",
          desc: "Ausführbare Dateien.",
          children: [
            {
              type: "file",
              name: "centralos",
              kind: "config",
              size: 65536,
              date: "—",
              content: ["[binary — 65536 Bytes]"],
            },
            {
              type: "file",
              name: "carrier-daemon",
              kind: "config",
              size: 18240,
              date: "—",
              content: ["[binary — 18240 Bytes]"],
            },
          ],
        },
        {
          type: "dir",
          name: "share",
          desc: "Gemeinsam genutzte Daten.",
          children: [
            {
              type: "file",
              name: "README",
              kind: "text",
              size: 200,
              date: "—",
              content: [
                "CentralOS v2.3 — Sektor-Betriebssystem.",
                "Dokumentation: /etc/motd, /system/handbuch_p14.txt.",
              ],
            },
            {
              type: "file",
              name: "CHANGELOG",
              kind: "text",
              size: 420,
              date: "—",
              content: [
                "── CentralOS Changelog ────────────────────────",
                "v2.3.1 11/1997 Outbound report endpoint repariert.",
                "v2.3  11/1997  Handbuch §14 überarbeitet.",
                "v2.2  03/1995  Resonanz-Feedback stabilisiert.",
                "v2.1  06/1994  Leitstelle 001 als Standardroute.",
                "v2.0  09/1991  Carrier-Daemon eingeführt.",
                "v1.4  05/1988  Erstauslieferung Sektor E67.",
              ],
            },
            {
              type: "file",
              name: "LICENSE",
              kind: "text",
              size: 200,
              date: "—",
              content: [
                "CentralOS — proprietär. Eigentum: Stadtwerke.",
                "Vervielfältigung, Reverse Engineering und",
                "Abschaltung sind untersagt. §11 SektorVO.",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "lib",
          desc: "Bibliotheken.",
          children: [
            {
              type: "file",
              name: "libcarrier.so",
              kind: "config",
              size: 24576,
              date: "—",
              content: ["[binary — 24576 Bytes]"],
            },
            {
              type: "file",
              name: "libresonance.so",
              kind: "config",
              size: 16384,
              date: "—",
              content: ["[binary — 16384 Bytes]"],
            },
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "bin",
      desc: "Grundlegende Befehle.",
      children: [
        {
          type: "file",
          name: "sh",
          kind: "config",
          size: 8192,
          date: "—",
          content: ["[binary — 8192 Bytes]"],
        },
        {
          type: "file",
          name: "ls",
          kind: "config",
          size: 2048,
          date: "—",
          content: ["[binary — 2048 Bytes]"],
        },
        {
          type: "file",
          name: "cat",
          kind: "config",
          size: 1920,
          date: "—",
          content: ["[binary — 1920 Bytes]"],
        },
        {
          type: "file",
          name: "cd",
          kind: "config",
          size: 1024,
          date: "—",
          content: ["[builtin]"],
        },
        {
          type: "file",
          name: "pwd",
          kind: "config",
          size: 1024,
          date: "—",
          content: ["[binary — 1024 Bytes]"],
        },
        {
          type: "file",
          name: "tree",
          kind: "config",
          size: 3840,
          date: "—",
          content: ["[binary — 3840 Bytes]"],
        },
        {
          type: "file",
          name: "echo",
          kind: "config",
          size: 720,
          date: "—",
          content: ["[binary — 720 Bytes]"],
        },
        {
          type: "file",
          name: "grep",
          kind: "config",
          size: 5120,
          date: "—",
          content: ["[binary — 5120 Bytes]"],
        },
      ],
    },
    {
      type: "dir",
      name: "tmp",
      desc: "Flüchtige Daten.",
      children: [
        {
          type: "file",
          name: ".placeholder",
          kind: "text",
          size: 0,
          date: "—",
          content: ["(leer)"],
        },
        {
          type: "file",
          name: "scratch.txt",
          kind: "text",
          size: 180,
          date: "—",
          content: [
            "[Notiz, vermutlich von gestern]",
            "- Insa anrufen wegen Gateway",
            "- 104,6 nicht ausschalten (Schmerz!)",
            "- B2 nachfüllen",
            "- Philippe meidet die Tür",
          ],
        },
        {
          type: "file",
          name: "core.dump",
          kind: "log",
          size: 4096,
          date: "06.11.1997",
          content: [
            "[core dump — carrier-daemon]",
            "signal SIGRES (Resonanz-Spitze)",
            "frame 0x0046  carrier_loop()",
            "frame 0x0021  feedback_send()",
            "frame 0x0008  main()",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "dev",
      desc: "Geräte.",
      children: [
        {
          type: "file",
          name: "null",
          kind: "config",
          size: 0,
          date: "—",
          content: [""],
        },
        {
          type: "file",
          name: "carrier0",
          kind: "config",
          size: 0,
          date: "—",
          content: [
            "[device — Trägersignal 104.600 MHz]",
            "Lesen = Signal aufzeichnen.",
            "Schreiben = nicht erlaubt.",
          ],
        },
        {
          type: "file",
          name: "radio0",
          kind: "config",
          size: 0,
          date: "—",
          content: ["[device — Schmerz-Radio Empfänger]"],
        },
        {
          type: "file",
          name: "tty0",
          kind: "config",
          size: 0,
          date: "—",
          content: ["[device — Terminal]"],
        },
        {
          type: "file",
          name: "random",
          kind: "config",
          size: 0,
          date: "—",
          content: [
            "[device — Zufallszahlen]",
            "Hinweis: Auf CentralOS deterministisch.",
          ],
        },
        {
          type: "file",
          name: "zero",
          kind: "config",
          size: 0,
          date: "—",
          content: ["[device — Endloser Nullstrom]"],
        },
        {
          type: "file",
          name: "leitstelle",
          kind: "config",
          size: 0,
          date: "—",
          content: [
            "[device — direkter Draht zur Leitstelle 001]",
            "Lesen: zuhören. Schreiben: gemeldet werden.",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "opt",
      desc: "Optionale Pakete.",
      children: [
        {
          type: "dir",
          name: "leitstelle-tools",
          desc: "Werkzeuge der Leitstelle.",
          children: [
            {
              type: "file",
              name: "README",
              kind: "text",
              size: 280,
              date: "—",
              content: [
                "── leitstelle-tools v1.4 ──────────────────────",
                "Internes Werkzeugset der Leitstelle 001.",
                "Installation auf Bewohnergeräten ist Policy-",
                "verstoß §11.2. Für Auditzwecke schreibgeschützt",
                "vorhanden.",
              ],
            },
            {
              type: "file",
              name: "trace",
              kind: "config",
              size: 9216,
              date: "—",
              content: ["[binary — 9216 Bytes]"],
            },
          ],
        },
      ],
    },
  ],
};

/** Resolve a path array (e.g. ['home','worag','tagebuch']) starting from root. */
export function resolveWorag(parts: string[]): FsNode | null {
  let node: FsNode = FILESYSTEM_WORAG;
  for (const p of parts) {
    if (node.type !== "dir") return null;
    const child: FsNode | undefined = node.children.find((c) => c.name === p);
    if (!child) return null;
    node = child;
  }
  return node;
}

export function pathStringWorag(parts: string[]): string {
  return "/" + parts.join("/");
}
