export interface FsFile {
  type: "file";
  name: string;
  kind?: "text" | "log" | "image" | "news" | "mail" | "audio" | "config";
  size?: number;
  date?: string;
  /** Optional StoryFlag required to reveal this file. */
  requires?: string;
  content: string[];
}

export interface FsDir {
  type: "dir";
  name: string;
  desc?: string;
  children: FsNode[];
}

export type FsNode = FsFile | FsDir;

/**
 * Virtual filesystem of CentralOS — accessible from the Terminal via
 * `ls`, `cd`, `cat`, `tree`, `pwd`. Hidden files appear once their
 * `requires` StoryFlag is set in the GameContext.
 *
 * Root layout follows a Unix-like convention. The player's home is
 * `/home/worag` — the Terminal starts there.
 */
const HOME_WORAG: FsDir = {
  type: "dir",
  name: "worag",
  desc: "Persönliches Verzeichnis — Worag, L.",
  children: [
    {
      type: "file",
      name: "adventure.bin",
      kind: "config",
      size: 4096,
      date: "21.08.1996",
      content: [
        "[ausführbare Datei — 4096 Bytes]",
        "",
        "Dies ist ein Programm. Tippe ins Terminal:",
        "    adventure",
        "oder:",
        "    ./adventure.bin",
        "um es zu starten.",
        "",
        "── HEADER ────────────────────────────────────────",
        "Titel:  »Ein Tag draußen«",
        "Autor:  L. Worag, Zimmer 2611",
        "Notiz:  Geschrieben in 14 Nachtschichten zwischen",
        "        dem 7. August und 21. August 1996.",
        "        Setting: Berlin, ca. 2026.",
        "        Quelle: was übrig war.",
        "── Ende ──────────────────────────────────────────",
      ],
    },
    {
      type: "dir",
      name: "tagebuch",
      desc: "Private Einträge. Verschlüsselt — Schicht 0.",
      children: [
        {
          type: "file",
          name: "1986-09-12.txt",
          kind: "text",
          size: 2148,
          date: "12.09.1986",
          content: [
            "── Eintrag, 12. September 1986 ─────────────────",
            "",
            "Heute wurde ich zugewiesen. Quadrant E67, Zimmer 2611.",
            "Sie haben mir gesagt, das sei vorübergehend. Drei Monate,",
            "vielleicht ein halbes Jahr, bis sich die Lage »stabilisiert«.",
            "",
            "Insa hat mich zum Aufzug begleitet. Sie hat mir den",
            "kleinen Empfänger gegeben — graues Plastik, ein Knopf,",
            "ein Drehrad. »Sender 104.6«, hat sie gesagt.",
            "»Lass es immer leise laufen. Du gewöhnst dich daran.",
            "Du wirst es nicht mehr ausschalten wollen.«",
            "",
            "Sie hatte recht.",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1989-04-03.txt",
          kind: "text",
          size: 1894,
          date: "03.04.1989",
          content: [
            "── Eintrag, 3. April 1989 ─────────────────────",
            "",
            "Drei Jahre. Niemand hat mehr »vorübergehend« gesagt.",
            "",
            "Mein Nachbar — Philippe, zwei Türen weiter — hat",
            "angefangen, gegen die Wand zu schlagen, wenn das",
            "Radio ausfällt. Heute Morgen war es zwölf Minuten",
            "still. Ich habe seine Faust durch zwei Wände gehört.",
            "",
            "Als der Träger zurückkam, hat er aufgehört. Sofort.",
            "Wie ein Hund, dem man den Napf hinstellt.",
            "",
            "Ich frage mich, wie ich aussehe, wenn es bei mir aussetzt.",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1993-11-30.txt",
          kind: "text",
          size: 1620,
          date: "30.11.1993",
          content: [
            "── Eintrag, 30. November 1993 ─────────────────",
            "",
            "Sieben Jahre. Ich habe heute zum ersten Mal über",
            "die Frequenz nachgedacht — nicht über das, was sie",
            "spielt, sondern darüber, was sie ist.",
            "",
            "Sinusförmig, würde ich sagen. Aber zu sauber für",
            "Musik. Und der Bass, der nicht da sein sollte —",
            "ich höre ihn in den Zähnen, bevor ich ihn im Ohr höre.",
            "",
            "Wenn das ein Trägersignal ist: Was wird getragen?",
            "Und in welche Richtung?",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1996-12-24.txt",
          kind: "text",
          size: 1102,
          date: "24.12.1996",
          content: [
            "── Eintrag, 24. Dezember 1996 ─────────────────",
            "",
            "Ich habe heute versucht, das Radio auszuschalten.",
            "Eine Sekunde. Mehr nicht.",
            "",
            "Ich kann es nicht beschreiben. Es war, als würde",
            "jemand mit einem Messer die Innenseite meines",
            "Schädels ausschaben. Insa hat mich angerufen, drei",
            "Minuten später. Sie hat nichts gesagt. Sie hat nur",
            "gewartet, bis ich es wieder eingeschaltet habe.",
            "",
            "Sie wusste es. Bevor ich es selbst gewusst habe.",
            "── Ende ────────────────────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1997-11-05.txt",
          kind: "text",
          size: 980,
          date: "05.11.1997",
          content: [
            "── Eintrag, 5. November 1997 ──────────────────",
            "",
            "Morgen ist Wartung. Insa hat angedeutet, dass",
            "etwas geschehen wird. Sie hat es nicht gesagt,",
            "aber sie hat zweimal das Wort »Verantwortung«",
            "fallen lassen. Bei ihr heißt das immer dasselbe.",
            "",
            "Ich bin bereit. Glaube ich.",
            "── Ende ────────────────────────────────────────",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "gedanken",
      desc: "Lose Notizen. Nicht sortiert.",
      children: [
        {
          type: "file",
          name: "resonanz.md",
          kind: "text",
          size: 612,
          date: "—",
          content: [
            "# Resonanz",
            "",
            "Resonanz ist, wenn ein Körper einen anderen zum",
            "Schwingen bringt, ohne ihn zu berühren. Nur über",
            "die Luft. Nur über die richtige Frequenz.",
            "",
            "Frage: Wenn 104.6 mich zum Schwingen bringt —",
            "wer ist der andere Körper?",
            "",
            "Antwort: Vielleicht nicht ein Körper. Vielleicht",
            "ein Gebäude. Vielleicht der ganze Sektor.",
          ],
        },
        {
          type: "file",
          name: "stille.md",
          kind: "text",
          size: 384,
          date: "—",
          content: [
            "# Stille",
            "",
            "Ich kann mich nicht erinnern, wie Stille klingt.",
            "Das ist kein Bild. Das ist eine Aussage.",
            "",
            "Ich habe es einmal versucht aufzuschreiben:",
            "»Stille ist ___.«",
            "Die Lücke ist seit elf Jahren leer.",
          ],
        },
        {
          type: "file",
          name: "philippe.md",
          kind: "text",
          size: 540,
          date: "—",
          content: [
            "# Philippe",
            "",
            "Er denkt, er sei mein Freund. Er ist es nicht.",
            "Er ist die Wand, gegen die ich schaue, wenn ich",
            "nicht in den Spiegel sehen will.",
            "",
            "Wenn ich ihn schreien höre, weiß ich, dass mein",
            "Empfänger noch funktioniert. Das ist die einzige",
            "Funktion, die er für mich erfüllt.",
            "",
            "Trotzdem: Wenn er stirbt, will ich daneben stehen.",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "bilder",
      desc: "ASCII-Archiv. Bilder werden im Sektor nicht mehr gedruckt.",
      children: [
        {
          type: "file",
          name: "fenster.ascii",
          kind: "image",
          size: 410,
          date: "1991",
          content: [
            "  ┌──────────────────────────┐",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  │ ░░░░░░░░░░░░░░░░░░░░░░░░ │",
            "  └──────────────────────────┘",
            "",
            "Bildtitel: »Fenster, Zimmer 2611«",
            "Aufgenommen: 14.07.1991",
            "Notiz: Beton, grau. Es gibt kein Glas.",
          ],
        },
        {
          type: "file",
          name: "insa.ascii",
          kind: "image",
          size: 720,
          date: "1986",
          content: [
            "        .--‾‾--.",
            "       /  o  o  \\",
            "      |    ><    |",
            "      |  \\____/  |",
            "       \\        /",
            "        ‘------’",
            "",
            "Bildtitel: »I. B. — Leitstelle, erster Tag«",
            "Datum: 12.09.1986",
            "Notiz: Sie hat damals noch gelächelt.",
          ],
        },
        {
          type: "file",
          name: "korridor.ascii",
          kind: "image",
          size: 690,
          date: "1995",
          content: [
            "  ╔══════════════════════════╗",
            "  ║  ▓▓                  ▓▓  ║",
            "  ║  ▓▓   ─── ─── ───    ▓▓  ║",
            "  ║  ▓▓                  ▓▓  ║",
            "  ║  ▓▓ [2611]    [2613] ▓▓  ║",
            "  ║  ▓▓                  ▓▓  ║",
            "  ║  ▓▓ ░░░░░░░░░░░░░░░░ ▓▓  ║",
            "  ╚══════════════════════════╝",
            "",
            "Bildtitel: »Korridor 26, abends«",
            "Notiz: Die Lampen flackern im Takt von 104.6.",
          ],
        },
        {
          type: "file",
          name: "vater.ascii",
          kind: "image",
          size: 510,
          date: "1984",
          requires: "metMikael",
          content: [
            "       ___",
            "      /   \\",
            "     | o o |",
            "     |  ─  |",
            "     |\\___/|",
            "    /|     |\\",
            "",
            "Bildtitel: »M. B. — vor der Zuweisung«",
            "Datum: 02.02.1984",
            "Notiz: Insas Vater. Bevor er nach E71 ging.",
            "Er hat dieses Foto in seiner Westentasche.",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "presse",
      desc: "Zeitungsausschnitte. Aus der Zentral-Datenbank kopiert.",
      children: [
        {
          type: "file",
          name: "1985_freie-presse.txt",
          kind: "news",
          size: 1820,
          date: "23.05.1985",
          content: [
            "── DIE FREIE PRESSE — 23. Mai 1985 ────────────",
            "Seite 3, Lokales",
            "",
            "       SEKTOR E67 GEHT IN BETRIEB",
            "",
            "Nach achtzehn Monaten Bauzeit wurde gestern der",
            "Wohnsektor E67 an das städtische Versorgungsnetz",
            "angeschlossen. Insgesamt 4.612 Wohnungen sollen",
            "Familien aufnehmen, die im Zuge der Stadtkern-",
            "verdichtung umgesiedelt werden.",
            "",
            "»Eine Lösung für eine ganze Generation«,",
            "kommentierte ein Sprecher der Stadtwerke.",
            "",
            "Über das in der Sektorzentrale installierte",
            "Funksystem — Frequenz 104.6 MHz — sollen die",
            "Bewohner mit Informationen versorgt werden.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1988_morgenblatt.txt",
          kind: "news",
          size: 1430,
          date: "07.10.1988",
          content: [
            "── MORGENBLATT — 7. Oktober 1988 ──────────────",
            "Seite 7, Vermischtes",
            "",
            "    KLAGEN ÜBER OHRENSCHMERZEN IN E67",
            "",
            "Bewohner des Sektors E67 berichten zunehmend",
            "über Druckgefühl und »inneres Brummen«. Der",
            "ärztliche Dienst der Stadt verweist auf den",
            "noch jungen Bau und die ungewohnte Akustik der",
            "Betonkorridore.",
            "",
            "Ein Zusammenhang mit dem sektoreigenen Funkkanal",
            "104.6 sei »technisch ausgeschlossen«, so die",
            "Stadtwerke. Eine Untersuchung wurde abgelehnt.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1991_abendkurier.txt",
          kind: "news",
          size: 1690,
          date: "29.03.1991",
          content: [
            "── ABENDKURIER — 29. März 1991 ────────────────",
            "Seite 1, Aufmacher",
            "",
            "       UNFALL IM SEKTOR E71 — DREI TOTE",
            "",
            "Bei einem nicht näher benannten Zwischenfall im",
            "Versorgungsschacht 14 des Sektors E71 sind in",
            "der Nacht zum Donnerstag drei Techniker ums",
            "Leben gekommen. Die Stadtwerke sprechen von",
            "einem »akustischen Resonanzereignis«.",
            "",
            "Augenzeugen berichten, dass die Männer »wie auf",
            "Befehl« stehen geblieben seien, kurz bevor der",
            "Schacht einstürzte. Ein Sprecher dementierte",
            "Berichte, wonach die sektoreigene Frequenz an-",
            "gehoben worden sei.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1994_stadtanzeiger.txt",
          kind: "news",
          size: 1280,
          date: "11.06.1994",
          content: [
            "── STADTANZEIGER — 11. Juni 1994 ──────────────",
            "Seite 5, Politik",
            "",
            "  STADT ÜBERTRÄGT FUNKLIZENZEN AN »LEITSTELLE«",
            "",
            "Die städtische Funklizenz für die Frequenz",
            "104.6 wurde gestern offiziell an die neu",
            "gegründete »Leitstelle für Sektorale Versorgung«",
            "übergeben. Über die genaue Trägerschaft der",
            "Leitstelle liegen widersprüchliche Angaben vor.",
            "",
            "Anfragen unserer Redaktion blieben unbeantwortet.",
            "── Ende des Artikels ─────────────────────────",
          ],
        },
        {
          type: "file",
          name: "1997_REDAKTIONSNOTIZ.txt",
          kind: "news",
          size: 760,
          date: "01.11.1997",
          requires: "heardMikaelTruth",
          content: [
            "── INTERNE REDAKTIONSNOTIZ — 1. Nov. 1997 ─────",
            "NICHT ZUR VERÖFFENTLICHUNG",
            "",
            "Quelle (anonym, ehem. Techniker E71) bestätigt:",
            "Der »Pain-Channel« auf 104.6 ist KEIN Sender,",
            "sondern eine Schleife. Die Hörer sind zugleich",
            "die Sender. Was über die Träger-Resonanz zurück-",
            "gespiegelt wird, dient der Leitstelle zur",
            "Lokalisierung und Verhaltensanalyse.",
            "",
            "Empfehlung: Story zurückhalten. Quellenschutz.",
            "── Ende ──────────────────────────────────────",
          ],
        },
      ],
    },
  ],
};

/** Where the terminal starts ("cd ~" returns here). */
export const HOME_PATH: string[] = ["home", "worag"];

const SYSTEM_DIR: FsDir = {
  type: "dir",
  name: "system",
  desc: "Konfigurationsdateien. Ändern auf eigene Gefahr.",
  children: [
    {
      type: "file",
      name: "carrier.cfg",
      kind: "config",
      size: 290,
      date: "—",
      content: [
        "# carrier.cfg — Trägerkonfiguration Quadrant E67",
        "frequency      = 104.600 MHz",
        "modulation     = AM-RES (proprietär)",
        "duty_cycle     = 100%",
        "user_shutdown  = DENY",
        "leitstelle     = 001",
        "feedback_loop  = ENABLED   # siehe HANDBUCH §14",
      ],
    },
    {
      type: "file",
      name: "handbuch_p14.txt",
      kind: "config",
      size: 540,
      date: "—",
      content: [
        "── HANDBUCH §14 — Feedback-Schleife ───────────",
        "",
        "Die Trägerfrequenz 104.6 ist als bidirektionale",
        "Resonanzschleife ausgelegt. Empfänger im Sektor",
        "fungieren als passive Sender. Eine vollständige",
        "Abschaltung ist auf Bewohnerseite nicht vorgesehen.",
        "",
        "Bei Versuch der Abschaltung wird automatisch",
        "ein Eskalationsprotokoll an Leitstelle 001",
        "ausgelöst.",
        "",
        "[Abschnitt überarbeitet: 11/1997]",
        "── Ende ──────────────────────────────────────",
      ],
    },
    {
      type: "file",
      name: ".hidden_log",
      kind: "log",
      size: 1100,
      date: "—",
      requires: "calledLeitstelle",
      content: [
        "── audit.log [Auszug, automatisch generiert] ──",
        "",
        "1997-11-06 09:14:02  USER worag  KEYPRESS volume--",
        "1997-11-06 09:14:03  ALERT carrier-attenuation",
        "1997-11-06 09:14:03  AUTODIAL leitstelle/001",
        "1997-11-06 09:14:11  CALL ANSWERED [BAUERFEIND, I.]",
        "1997-11-06 09:14:42  USER worag  RESTORE volume",
        "1997-11-06 09:14:42  ALERT cleared",
        "",
        "── Hinweis: Eintrag wird in 30 Tagen rotiert. ──",
      ],
    },
  ],
};

/** Unix-like root. The player starts in /home/worag. */
export const FILESYSTEM: FsDir = {
  type: "dir",
  name: "",
  desc: "CentralOS Wurzelverzeichnis",
  children: [
    SYSTEM_DIR,
    {
      type: "dir",
      name: "home",
      desc: "Benutzerverzeichnisse.",
      children: [
        HOME_WORAG,
      ],
    },
    {
      type: "dir",
      name: "etc",
      desc: "Systemkonfiguration.",
      children: [
        {
          type: "file",
          name: "hosts",
          kind: "config",
          size: 180,
          date: "—",
          content: [
            "# /etc/hosts — CentralOS",
            "127.0.0.1    localhost",
            "10.67.0.1    gateway.e67",
            "10.67.0.2    leitstelle.e67   # 001",
            "10.71.0.1    gateway.e71",
            "10.71.15.34  sprechzimmer.e71",
          ],
        },
        {
          type: "file",
          name: "passwd",
          kind: "config",
          size: 210,
          date: "—",
          content: [
            "# /etc/passwd — Auszug",
            "root:x:0:0:CentralOS:/root:/bin/sh",
            "worag:x:2611:100:Worag, L.:/home/worag:/bin/sh",
            "leitstelle:x:1:1:Leitstelle 001:/var/leitstelle:/bin/false",
          ],
        },
        {
          type: "file",
          name: "motd",
          kind: "text",
          size: 240,
          date: "—",
          content: [
            "── CentralOS v2.3 ─────────────────────────────",
            "Willkommen, Bewohner.",
            "Respektieren Sie die Sektorordnung.",
            "Frequenz 104,6 ist verpflichtend.",
            "Störungen: 001.",
          ],
        },
        {
          type: "file",
          name: "sektor.conf",
          kind: "config",
          size: 300,
          date: "—",
          content: [
            "# /etc/sektor.conf",
            "sektor        = E67",
            "korridor      = 26",
            "gateway       = E67/E71",
            "frequency     = 104.600 MHz",
            "quiet_hours   = none",
          ],
        },
        {
          type: "file",
          name: "fstab",
          kind: "config",
          size: 260,
          date: "—",
          content: [
            "# /etc/fstab — CentralOS",
            "# device           mount         type     opts",
            "/dev/sda1          /             ext2     ro,sync",
            "/dev/sda2          /home         ext2     rw",
            "/dev/carrier0      /var/carrier  pcmstrm  ro",
            "tmpfs              /tmp          tmpfs    rw,size=4M",
          ],
        },
        {
          type: "file",
          name: "resolv.conf",
          kind: "config",
          size: 120,
          date: "—",
          content: [
            "# /etc/resolv.conf",
            "nameserver  10.67.0.1",
            "nameserver  10.0.0.1",
            "search      e67.zentrale",
          ],
        },
        {
          type: "file",
          name: "issue",
          kind: "text",
          size: 90,
          date: "—",
          content: [
            "CentralOS v2.3 — Quadrant E67",
            "Login: \\u   TTY: \\l",
          ],
        },
        {
          type: "file",
          name: "shadow",
          kind: "config",
          size: 140,
          date: "—",
          content: [
            "── /etc/shadow ────────────────────────────────",
            "cat: shadow: Zugriff verweigert.",
          ],
        },
        {
          type: "file",
          name: "cron.tab",
          kind: "config",
          size: 220,
          date: "—",
          content: [
            "# /etc/cron.tab",
            "# m  h  dom mon dow  cmd",
            "0   *  *   *   *    /usr/bin/carrier-daemon --keepalive",
            "0   3  *   *   *    /usr/bin/centralos --rotate-logs",
            "*/5 *  *   *   *    /opt/leitstelle-tools/trace --ping",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "var",
      desc: "Variable Daten, Logs.",
      children: [
        {
          type: "dir",
          name: "log",
          desc: "Systemlogs.",
          children: [
            {
              type: "file",
              name: "carrier.log",
              kind: "log",
              size: 820,
              date: "06.11.1997",
              content: [
                "── carrier.log ────────────────────────────────",
                "1997-11-06 06:00:00  carrier UP    104.600 MHz",
                "1997-11-06 06:00:01  duty_cycle    100%",
                "1997-11-06 09:14:02  user worag    volume--",
                "1997-11-06 09:14:03  carrier       attenuation",
                "1997-11-06 09:14:11  leitstelle    ACK",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "gateway.log",
              kind: "log",
              size: 420,
              date: "06.11.1997",
              content: [
                "── gateway.log ────────────────────────────────",
                "1997-11-06 08:12:00  gateway E67/E71  ERROR 4567",
                "1997-11-06 08:12:00  reason           maintenance",
                "1997-11-06 08:12:00  manual_code      REQUIRED",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "auth.log",
              kind: "log",
              size: 980,
              date: "06.11.1997",
              content: [
                "── auth.log ───────────────────────────────────",
                "1997-11-06 05:58:11  login worag        OK",
                "1997-11-06 06:02:44  sudo  worag        DENIED",
                "1997-11-06 07:21:09  login leitstelle   OK (remote)",
                "1997-11-06 07:21:11  cmd   leitstelle   tail /var/log/carrier.log",
                "1997-11-06 09:14:11  call  leitstelle/001  ANSWERED",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "kern.log",
              kind: "log",
              size: 540,
              date: "06.11.1997",
              content: [
                "── kern.log ───────────────────────────────────",
                "kernel: CentralOS 2.3 boot OK",
                "kernel: carrier0 attached at 104.600 MHz",
                "kernel: radio0 attached (rx-only)",
                "kernel: WARN /dev/null write throttled",
                "── Ende ───────────────────────────────────────",
              ],
            },
            {
              type: "file",
              name: "dmesg",
              kind: "log",
              size: 380,
              date: "—",
              content: [
                "[    0.00] CentralOS v2.3 starting",
                "[    0.12] cpu0: 33 MHz (synthetisch)",
                "[    0.40] mem: 4096 KB",
                "[    1.10] carrier0: lock 104.600 MHz",
                "[    1.11] resonance feedback loop ENABLED",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "mail",
          desc: "Postfächer.",
          children: [
            {
              type: "file",
              name: "worag",
              kind: "mail",
              size: 80,
              date: "—",
              content: [
                "Mailbox-Verweis — siehe 'inbox' im Terminal.",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "leitstelle",
          desc: "Leitstelle 001 — Zugriff verweigert.",
          children: [
            {
              type: "file",
              name: ".locked",
              kind: "text",
              size: 60,
              date: "—",
              content: ["Zugriff verweigert. Kontakt: 001."],
            },
          ],
        },
        {
          type: "dir",
          name: "spool",
          desc: "Spool-Verzeichnis.",
          children: [
            {
              type: "file",
              name: "cron.last",
              kind: "text",
              size: 80,
              date: "—",
              content: [
                "carrier-daemon  OK   06.11.1997 09:00",
                "centralos       OK   06.11.1997 03:00",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "carrier",
          desc: "Trägersignal-Aufzeichnungen.",
          children: [
            {
              type: "file",
              name: "rec.1997-11-06.bin",
              kind: "config",
              size: 524288,
              date: "06.11.1997",
              content: [
                "[binary — 524288 Bytes]",
                "Aufzeichnung Trägersignal 104.600 MHz, 6h.",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "usr",
      desc: "Installierte Programme.",
      children: [
        {
          type: "dir",
          name: "bin",
          desc: "Ausführbare Dateien.",
          children: [
            {
              type: "file",
              name: "centralos",
              kind: "config",
              size: 65536,
              date: "—",
              content: ["[binary — 65536 Bytes]"],
            },
            {
              type: "file",
              name: "carrier-daemon",
              kind: "config",
              size: 18240,
              date: "—",
              content: ["[binary — 18240 Bytes]"],
            },
          ],
        },
        {
          type: "dir",
          name: "share",
          desc: "Gemeinsam genutzte Daten.",
          children: [
            {
              type: "file",
              name: "README",
              kind: "text",
              size: 200,
              date: "—",
              content: [
                "CentralOS v2.3 — Sektor-Betriebssystem.",
                "Dokumentation: /etc/motd, /system/handbuch_p14.txt.",
              ],
            },
            {
              type: "file",
              name: "CHANGELOG",
              kind: "text",
              size: 420,
              date: "—",
              content: [
                "── CentralOS Changelog ────────────────────────",
                "v2.3  11/1997  Handbuch §14 überarbeitet.",
                "v2.2  03/1995  Resonanz-Feedback stabilisiert.",
                "v2.1  06/1994  Leitstelle 001 als Standardroute.",
                "v2.0  09/1991  Carrier-Daemon eingeführt.",
                "v1.4  05/1988  Erstauslieferung Sektor E67.",
              ],
            },
            {
              type: "file",
              name: "LICENSE",
              kind: "text",
              size: 200,
              date: "—",
              content: [
                "CentralOS — proprietär. Eigentum: Stadtwerke.",
                "Vervielfältigung, Reverse Engineering und",
                "Abschaltung sind untersagt. §11 SektorVO.",
              ],
            },
          ],
        },
        {
          type: "dir",
          name: "lib",
          desc: "Bibliotheken.",
          children: [
            {
              type: "file",
              name: "libcarrier.so",
              kind: "config",
              size: 24576,
              date: "—",
              content: ["[binary — 24576 Bytes]"],
            },
            {
              type: "file",
              name: "libresonance.so",
              kind: "config",
              size: 16384,
              date: "—",
              content: ["[binary — 16384 Bytes]"],
            },
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "bin",
      desc: "Grundlegende Befehle.",
      children: [
        {
          type: "file",
          name: "sh",
          kind: "config",
          size: 8192,
          date: "—",
          content: ["[binary — 8192 Bytes]"],
        },
        {
          type: "file",
          name: "ls",
          kind: "config",
          size: 2048,
          date: "—",
          content: ["[binary — 2048 Bytes]"],
        },
        {
          type: "file",
          name: "cat",
          kind: "config",
          size: 1920,
          date: "—",
          content: ["[binary — 1920 Bytes]"],
        },
        {
          type: "file",
          name: "cd",
          kind: "config",
          size: 1024,
          date: "—",
          content: ["[builtin]"],
        },
        {
          type: "file",
          name: "pwd",
          kind: "config",
          size: 1024,
          date: "—",
          content: ["[binary — 1024 Bytes]"],
        },
        {
          type: "file",
          name: "tree",
          kind: "config",
          size: 3840,
          date: "—",
          content: ["[binary — 3840 Bytes]"],
        },
        {
          type: "file",
          name: "echo",
          kind: "config",
          size: 720,
          date: "—",
          content: ["[binary — 720 Bytes]"],
        },
        {
          type: "file",
          name: "grep",
          kind: "config",
          size: 5120,
          date: "—",
          content: ["[binary — 5120 Bytes]"],
        },
      ],
    },
    {
      type: "dir",
      name: "tmp",
      desc: "Flüchtige Daten.",
      children: [
        {
          type: "file",
          name: ".placeholder",
          kind: "text",
          size: 0,
          date: "—",
          content: ["(leer)"],
        },
        {
          type: "file",
          name: "scratch.txt",
          kind: "text",
          size: 180,
          date: "—",
          content: [
            "[Notiz, vermutlich von gestern]",
            "- Insa anrufen wegen Gateway",
            "- 104,6 nicht ausschalten (Schmerz!)",
            "- B2 nachfüllen",
            "- Philippe meidet die Tür",
          ],
        },
        {
          type: "file",
          name: "core.dump",
          kind: "log",
          size: 4096,
          date: "06.11.1997",
          content: [
            "[core dump — carrier-daemon]",
            "signal SIGRES (Resonanz-Spitze)",
            "frame 0x0046  carrier_loop()",
            "frame 0x0021  feedback_send()",
            "frame 0x0008  main()",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "dev",
      desc: "Geräte.",
      children: [
        {
          type: "file",
          name: "null",
          kind: "config",
          size: 0,
          date: "—",
          content: [""],
        },
        {
          type: "file",
          name: "carrier0",
          kind: "config",
          size: 0,
          date: "—",
          content: [
            "[device — Trägersignal 104.600 MHz]",
            "Lesen = Signal aufzeichnen.",
            "Schreiben = nicht erlaubt.",
          ],
        },
        {
          type: "file",
          name: "radio0",
          kind: "config",
          size: 0,
          date: "—",
          content: ["[device — Schmerz-Radio Empfänger]"],
        },
        {
          type: "file",
          name: "tty0",
          kind: "config",
          size: 0,
          date: "—",
          content: ["[device — Terminal]"],
        },
        {
          type: "file",
          name: "random",
          kind: "config",
          size: 0,
          date: "—",
          content: [
            "[device — Zufallszahlen]",
            "Hinweis: Auf CentralOS deterministisch.",
          ],
        },
        {
          type: "file",
          name: "zero",
          kind: "config",
          size: 0,
          date: "—",
          content: ["[device — Endloser Nullstrom]"],
        },
        {
          type: "file",
          name: "leitstelle",
          kind: "config",
          size: 0,
          date: "—",
          content: [
            "[device — direkter Draht zur Leitstelle 001]",
            "Lesen: zuhören. Schreiben: gemeldet werden.",
          ],
        },
      ],
    },
    {
      type: "dir",
      name: "opt",
      desc: "Optionale Pakete.",
      children: [
        {
          type: "dir",
          name: "leitstelle-tools",
          desc: "Werkzeuge der Leitstelle.",
          children: [
            {
              type: "file",
              name: "README",
              kind: "text",
              size: 280,
              date: "—",
              content: [
                "── leitstelle-tools v1.4 ──────────────────────",
                "Internes Werkzeugset der Leitstelle 001.",
                "Installation auf Bewohnergeräten ist Policy-",
                "verstoß §11.2. Für Auditzwecke schreibgeschützt",
                "vorhanden.",
              ],
            },
            {
              type: "file",
              name: "trace",
              kind: "config",
              size: 9216,
              date: "—",
              content: ["[binary — 9216 Bytes]"],
            },
          ],
        },
      ],
    },
  ],
};

/** Resolve a path array (e.g. ['home','worag','tagebuch']) starting from root. */
export function resolvePath(parts: string[]): FsNode | null {
  let node: FsNode = FILESYSTEM;
  for (const p of parts) {
    if (node.type !== "dir") return null;
    const child: FsNode | undefined = node.children.find((c) => c.name === p);
    if (!child) return null;
    node = child;
  }
  return node;
}

export function pathString(parts: string[]): string {
  return "/" + parts.join("/");
}
