/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DsaRouteImport } from './routes/dsa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DsaIndexRouteImport } from './routes/dsa.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DsaHeldenRouteImport } from './routes/dsa.helden'
import { Route as DsaGruppeRouteImport } from './routes/dsa.gruppe'
import { Route as DsaSlotRouteImport } from './routes/dsa.$slot'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as DsaGruppeRoomIdRouteImport } from './routes/dsa.gruppe.$roomId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicNpcMemoryUpdateRouteImport } from './routes/api/public/npc-memory-update'
import { Route as ApiPublicNpcChatRouteImport } from './routes/api/public/npc-chat'
import { Route as ApiPublicMarvOilRouteImport } from './routes/api/public/marv-oil'
import { Route as ApiPublicFastwebChatRouteImport } from './routes/api/public/fastweb-chat'
import { Route as ApiPublicDsaMasterRouteImport } from './routes/api/public/dsa-master'
import { Route as ApiPublicDsaGroupRouteImport } from './routes/api/public/dsa-group'
import { Route as ApiPublicDonationCheckoutRouteImport } from './routes/api/public/donation-checkout'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as DsaGruppeRoomIdSpielRouteImport } from './routes/dsa.gruppe.$roomId.spiel'
import { Route as ApiPublicHooksWeeklySignupSummaryRouteImport } from './routes/api/public/hooks/weekly-signup-summary'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaRoute = DsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaIndexRoute = DsaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DsaRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaHeldenRoute = DsaHeldenRouteImport.update({
  id: '/helden',
  path: '/helden',
  getParentRoute: () => DsaRoute,
} as any)
const DsaGruppeRoute = DsaGruppeRouteImport.update({
  id: '/gruppe',
  path: '/gruppe',
  getParentRoute: () => DsaRoute,
} as any)
const DsaSlotRoute = DsaSlotRouteImport.update({
  id: '/$slot',
  path: '/$slot',
  getParentRoute: () => DsaRoute,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaGruppeRoomIdRoute = DsaGruppeRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => DsaGruppeRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNpcMemoryUpdateRoute =
  ApiPublicNpcMemoryUpdateRouteImport.update({
    id: '/api/public/npc-memory-update',
    path: '/api/public/npc-memory-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNpcChatRoute = ApiPublicNpcChatRouteImport.update({
  id: '/api/public/npc-chat',
  path: '/api/public/npc-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarvOilRoute = ApiPublicMarvOilRouteImport.update({
  id: '/api/public/marv-oil',
  path: '/api/public/marv-oil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFastwebChatRoute = ApiPublicFastwebChatRouteImport.update({
  id: '/api/public/fastweb-chat',
  path: '/api/public/fastweb-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDsaMasterRoute = ApiPublicDsaMasterRouteImport.update({
  id: '/api/public/dsa-master',
  path: '/api/public/dsa-master',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDsaGroupRoute = ApiPublicDsaGroupRouteImport.update({
  id: '/api/public/dsa-group',
  path: '/api/public/dsa-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDonationCheckoutRoute =
  ApiPublicDonationCheckoutRouteImport.update({
    id: '/api/public/donation-checkout',
    path: '/api/public/donation-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const DsaGruppeRoomIdSpielRoute = DsaGruppeRoomIdSpielRouteImport.update({
  id: '/spiel',
  path: '/spiel',
  getParentRoute: () => DsaGruppeRoomIdRoute,
} as any)
const ApiPublicHooksWeeklySignupSummaryRoute =
  ApiPublicHooksWeeklySignupSummaryRouteImport.update({
    id: '/api/public/hooks/weekly-signup-summary',
    path: '/api/public/hooks/weekly-signup-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dsa': typeof DsaRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/dsa/$slot': typeof DsaSlotRoute
  '/dsa/gruppe': typeof DsaGruppeRouteWithChildren
  '/dsa/helden': typeof DsaHeldenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/dsa/': typeof DsaIndexRoute
  '/api/public/donation-checkout': typeof ApiPublicDonationCheckoutRoute
  '/api/public/dsa-group': typeof ApiPublicDsaGroupRoute
  '/api/public/dsa-master': typeof ApiPublicDsaMasterRoute
  '/api/public/fastweb-chat': typeof ApiPublicFastwebChatRoute
  '/api/public/marv-oil': typeof ApiPublicMarvOilRoute
  '/api/public/npc-chat': typeof ApiPublicNpcChatRoute
  '/api/public/npc-memory-update': typeof ApiPublicNpcMemoryUpdateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dsa/gruppe/$roomId': typeof DsaGruppeRoomIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/weekly-signup-summary': typeof ApiPublicHooksWeeklySignupSummaryRoute
  '/dsa/gruppe/$roomId/spiel': typeof DsaGruppeRoomIdSpielRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/dsa/$slot': typeof DsaSlotRoute
  '/dsa/gruppe': typeof DsaGruppeRouteWithChildren
  '/dsa/helden': typeof DsaHeldenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/dsa': typeof DsaIndexRoute
  '/api/public/donation-checkout': typeof ApiPublicDonationCheckoutRoute
  '/api/public/dsa-group': typeof ApiPublicDsaGroupRoute
  '/api/public/dsa-master': typeof ApiPublicDsaMasterRoute
  '/api/public/fastweb-chat': typeof ApiPublicFastwebChatRoute
  '/api/public/marv-oil': typeof ApiPublicMarvOilRoute
  '/api/public/npc-chat': typeof ApiPublicNpcChatRoute
  '/api/public/npc-memory-update': typeof ApiPublicNpcMemoryUpdateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dsa/gruppe/$roomId': typeof DsaGruppeRoomIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/weekly-signup-summary': typeof ApiPublicHooksWeeklySignupSummaryRoute
  '/dsa/gruppe/$roomId/spiel': typeof DsaGruppeRoomIdSpielRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dsa': typeof DsaRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/dsa/$slot': typeof DsaSlotRoute
  '/dsa/gruppe': typeof DsaGruppeRouteWithChildren
  '/dsa/helden': typeof DsaHeldenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/dsa/': typeof DsaIndexRoute
  '/api/public/donation-checkout': typeof ApiPublicDonationCheckoutRoute
  '/api/public/dsa-group': typeof ApiPublicDsaGroupRoute
  '/api/public/dsa-master': typeof ApiPublicDsaMasterRoute
  '/api/public/fastweb-chat': typeof ApiPublicFastwebChatRoute
  '/api/public/marv-oil': typeof ApiPublicMarvOilRoute
  '/api/public/npc-chat': typeof ApiPublicNpcChatRoute
  '/api/public/npc-memory-update': typeof ApiPublicNpcMemoryUpdateRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dsa/gruppe/$roomId': typeof DsaGruppeRoomIdRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/weekly-signup-summary': typeof ApiPublicHooksWeeklySignupSummaryRoute
  '/dsa/gruppe/$roomId/spiel': typeof DsaGruppeRoomIdSpielRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dsa'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/api/tts'
    | '/dsa/$slot'
    | '/dsa/gruppe'
    | '/dsa/helden'
    | '/email/unsubscribe'
    | '/dsa/'
    | '/api/public/donation-checkout'
    | '/api/public/dsa-group'
    | '/api/public/dsa-master'
    | '/api/public/fastweb-chat'
    | '/api/public/marv-oil'
    | '/api/public/npc-chat'
    | '/api/public/npc-memory-update'
    | '/api/public/stripe-webhook'
    | '/dsa/gruppe/$roomId'
    | '/lovable/email/suppression'
    | '/api/public/hooks/weekly-signup-summary'
    | '/dsa/gruppe/$roomId/spiel'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/api/tts'
    | '/dsa/$slot'
    | '/dsa/gruppe'
    | '/dsa/helden'
    | '/email/unsubscribe'
    | '/dsa'
    | '/api/public/donation-checkout'
    | '/api/public/dsa-group'
    | '/api/public/dsa-master'
    | '/api/public/fastweb-chat'
    | '/api/public/marv-oil'
    | '/api/public/npc-chat'
    | '/api/public/npc-memory-update'
    | '/api/public/stripe-webhook'
    | '/dsa/gruppe/$roomId'
    | '/lovable/email/suppression'
    | '/api/public/hooks/weekly-signup-summary'
    | '/dsa/gruppe/$roomId/spiel'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/dsa'
    | '/sitemap.xml'
    | '/unsubscribe'
    | '/api/tts'
    | '/dsa/$slot'
    | '/dsa/gruppe'
    | '/dsa/helden'
    | '/email/unsubscribe'
    | '/dsa/'
    | '/api/public/donation-checkout'
    | '/api/public/dsa-group'
    | '/api/public/dsa-master'
    | '/api/public/fastweb-chat'
    | '/api/public/marv-oil'
    | '/api/public/npc-chat'
    | '/api/public/npc-memory-update'
    | '/api/public/stripe-webhook'
    | '/dsa/gruppe/$roomId'
    | '/lovable/email/suppression'
    | '/api/public/hooks/weekly-signup-summary'
    | '/dsa/gruppe/$roomId/spiel'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DsaRoute: typeof DsaRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicDonationCheckoutRoute: typeof ApiPublicDonationCheckoutRoute
  ApiPublicDsaGroupRoute: typeof ApiPublicDsaGroupRoute
  ApiPublicDsaMasterRoute: typeof ApiPublicDsaMasterRoute
  ApiPublicFastwebChatRoute: typeof ApiPublicFastwebChatRoute
  ApiPublicMarvOilRoute: typeof ApiPublicMarvOilRoute
  ApiPublicNpcChatRoute: typeof ApiPublicNpcChatRoute
  ApiPublicNpcMemoryUpdateRoute: typeof ApiPublicNpcMemoryUpdateRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksWeeklySignupSummaryRoute: typeof ApiPublicHooksWeeklySignupSummaryRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa': {
      id: '/dsa'
      path: '/dsa'
      fullPath: '/dsa'
      preLoaderRoute: typeof DsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa/': {
      id: '/dsa/'
      path: '/'
      fullPath: '/dsa/'
      preLoaderRoute: typeof DsaIndexRouteImport
      parentRoute: typeof DsaRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa/helden': {
      id: '/dsa/helden'
      path: '/helden'
      fullPath: '/dsa/helden'
      preLoaderRoute: typeof DsaHeldenRouteImport
      parentRoute: typeof DsaRoute
    }
    '/dsa/gruppe': {
      id: '/dsa/gruppe'
      path: '/gruppe'
      fullPath: '/dsa/gruppe'
      preLoaderRoute: typeof DsaGruppeRouteImport
      parentRoute: typeof DsaRoute
    }
    '/dsa/$slot': {
      id: '/dsa/$slot'
      path: '/$slot'
      fullPath: '/dsa/$slot'
      preLoaderRoute: typeof DsaSlotRouteImport
      parentRoute: typeof DsaRoute
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa/gruppe/$roomId': {
      id: '/dsa/gruppe/$roomId'
      path: '/$roomId'
      fullPath: '/dsa/gruppe/$roomId'
      preLoaderRoute: typeof DsaGruppeRoomIdRouteImport
      parentRoute: typeof DsaGruppeRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/npc-memory-update': {
      id: '/api/public/npc-memory-update'
      path: '/api/public/npc-memory-update'
      fullPath: '/api/public/npc-memory-update'
      preLoaderRoute: typeof ApiPublicNpcMemoryUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/npc-chat': {
      id: '/api/public/npc-chat'
      path: '/api/public/npc-chat'
      fullPath: '/api/public/npc-chat'
      preLoaderRoute: typeof ApiPublicNpcChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/marv-oil': {
      id: '/api/public/marv-oil'
      path: '/api/public/marv-oil'
      fullPath: '/api/public/marv-oil'
      preLoaderRoute: typeof ApiPublicMarvOilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fastweb-chat': {
      id: '/api/public/fastweb-chat'
      path: '/api/public/fastweb-chat'
      fullPath: '/api/public/fastweb-chat'
      preLoaderRoute: typeof ApiPublicFastwebChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dsa-master': {
      id: '/api/public/dsa-master'
      path: '/api/public/dsa-master'
      fullPath: '/api/public/dsa-master'
      preLoaderRoute: typeof ApiPublicDsaMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dsa-group': {
      id: '/api/public/dsa-group'
      path: '/api/public/dsa-group'
      fullPath: '/api/public/dsa-group'
      preLoaderRoute: typeof ApiPublicDsaGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/donation-checkout': {
      id: '/api/public/donation-checkout'
      path: '/api/public/donation-checkout'
      fullPath: '/api/public/donation-checkout'
      preLoaderRoute: typeof ApiPublicDonationCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa/gruppe/$roomId/spiel': {
      id: '/dsa/gruppe/$roomId/spiel'
      path: '/spiel'
      fullPath: '/dsa/gruppe/$roomId/spiel'
      preLoaderRoute: typeof DsaGruppeRoomIdSpielRouteImport
      parentRoute: typeof DsaGruppeRoomIdRoute
    }
    '/api/public/hooks/weekly-signup-summary': {
      id: '/api/public/hooks/weekly-signup-summary'
      path: '/api/public/hooks/weekly-signup-summary'
      fullPath: '/api/public/hooks/weekly-signup-summary'
      preLoaderRoute: typeof ApiPublicHooksWeeklySignupSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DsaGruppeRoomIdRouteChildren {
  DsaGruppeRoomIdSpielRoute: typeof DsaGruppeRoomIdSpielRoute
}

const DsaGruppeRoomIdRouteChildren: DsaGruppeRoomIdRouteChildren = {
  DsaGruppeRoomIdSpielRoute: DsaGruppeRoomIdSpielRoute,
}

const DsaGruppeRoomIdRouteWithChildren = DsaGruppeRoomIdRoute._addFileChildren(
  DsaGruppeRoomIdRouteChildren,
)

interface DsaGruppeRouteChildren {
  DsaGruppeRoomIdRoute: typeof DsaGruppeRoomIdRouteWithChildren
}

const DsaGruppeRouteChildren: DsaGruppeRouteChildren = {
  DsaGruppeRoomIdRoute: DsaGruppeRoomIdRouteWithChildren,
}

const DsaGruppeRouteWithChildren = DsaGruppeRoute._addFileChildren(
  DsaGruppeRouteChildren,
)

interface DsaRouteChildren {
  DsaSlotRoute: typeof DsaSlotRoute
  DsaGruppeRoute: typeof DsaGruppeRouteWithChildren
  DsaHeldenRoute: typeof DsaHeldenRoute
  DsaIndexRoute: typeof DsaIndexRoute
}

const DsaRouteChildren: DsaRouteChildren = {
  DsaSlotRoute: DsaSlotRoute,
  DsaGruppeRoute: DsaGruppeRouteWithChildren,
  DsaHeldenRoute: DsaHeldenRoute,
  DsaIndexRoute: DsaIndexRoute,
}

const DsaRouteWithChildren = DsaRoute._addFileChildren(DsaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DsaRoute: DsaRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicDonationCheckoutRoute: ApiPublicDonationCheckoutRoute,
  ApiPublicDsaGroupRoute: ApiPublicDsaGroupRoute,
  ApiPublicDsaMasterRoute: ApiPublicDsaMasterRoute,
  ApiPublicFastwebChatRoute: ApiPublicFastwebChatRoute,
  ApiPublicMarvOilRoute: ApiPublicMarvOilRoute,
  ApiPublicNpcChatRoute: ApiPublicNpcChatRoute,
  ApiPublicNpcMemoryUpdateRoute: ApiPublicNpcMemoryUpdateRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksWeeklySignupSummaryRoute:
    ApiPublicHooksWeeklySignupSummaryRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
